$axure.loadCurrentPage({
  "url":"签约管理.html",
  "generationDate":new Date(1516182759385.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"e04561cbaed84de8b4aff5631f67d88b",
    "type":"Axure:Page",
    "name":"签约管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"44400dde669c41389f17926359b544f1",
          "label":"bg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":1880,
              "height":1110}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"891c9f885ecb4a9fbbed00a2b61bf397",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ca53800ff7c41f4b426fd3b4e3d6f95",
                  "label":"",
                  "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":1880,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb0e011043c445f7828bab67c885a544",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":1880,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u1.png"}},
{
                  "id":"6fedadd6a06845aa884d948a34b689b9",
                  "label":"",
                  "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA4AAB6},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":1880,
                      "height":2380},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cd08a7ea871427dabd729b6919a31ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA4AAB6},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":1880,
                          "height":2380},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u3.png"}},
{
                  "id":"91d05286874048dbbb19739d68d73e3f",
                  "label":"",
                  "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":1489,
                      "y":17},
                    "size":{
                      "width":101,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e450e8c15084829968183409ee81240",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":1489,
                          "y":17},
                        "size":{
                          "width":101,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a8d5be12f504697a91fe3d9ed960426",
                  "label":"",
                  "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":1646,
                      "y":17},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76d1799bea314626a4efcc9b7e9958d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"44400dde669c41389f17926359b544f1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":1646,
                          "y":17},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"9360e160aa2542c699f06172ede62780",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":6},
            "size":{
              "width":10,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表（总览）/u19_line.png"}},
{
          "id":"ad32919471814d36b5d64fe8ba1deceb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":403,
              "y":16},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5408d3c6eef410db5d0cd201999bdc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":16},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a6c5bdad85746db988cdec15dd5fc05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":459,
              "y":80},
            "size":{
              "width":1131,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5778fc58d6844a3982b9305a6394bca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":459,
                  "y":80},
                "size":{
                  "width":1131,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工编辑个人资料/u24.png"}},
{
          "id":"e42438b570964727818354995046dc8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":270,
              "y":11},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd78b1b3eb7d42a9b0449d6a1db9446c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":11},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7dbe999582b47159e2f9fe06b35dc3f",
          "label":"r1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":274},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdea9a7b088b44e18e17afd0e53a6ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":274},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品管理/r1_u29.png"}},
{
          "id":"c408649ff1af4d5196d591f3e68f18a6",
          "label":"r2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":324},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e0e0d16c4a34dcfb059d0a3ee528734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":324},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 权限管理（职位权限）",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理（职位权限）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"2f68843b82044df095b71dbf1d66782a",
          "label":"r3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":374},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107c89477cb142d4aa34de9a5f4cadca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":374},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 部门管理",
                      "target":{
                        "targetType":"page",
                        "url":"部门管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"54ecce3cfaaf4ac7b634d33a32e63c19",
          "label":"r4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":424},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ea0fcb05c24119960cd5b041379752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":424},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 员工管理",
                      "target":{
                        "targetType":"page",
                        "url":"员工管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"75fdb691bb1b4b90abea3978b03bc722",
          "label":"r5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":474},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7800141611f461ca81415438053b651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":474},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户管理",
                      "target":{
                        "targetType":"page",
                        "url":"客户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"8683110268a14c4b807de18e4549a5d2",
          "label":"r6",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":524},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9b10b306d10457cb7a9c9fcced667a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":524},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 p6",
                      "objectsToFades":[{
                          "objectPath":["eb55c113e9d04068ad2cd598296c1b0b"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 p6 跟随",
                      "objectsToMoves":[{
                          "objectPath":["eb55c113e9d04068ad2cd598296c1b0b"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]},
{
                      "action":"moveWidget",
                      "description":"移动 r7 跟随",
                      "objectsToMoves":[{
                          "objectPath":["8480f2a9d5c04353a258d262d5f23f3f"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"eb55c113e9d04068ad2cd598296c1b0b",
          "label":"p6",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":573},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onShow":{
              "description":"OnShow",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 r7 到 ([[This.left]],[[This.bottom]])",
                      "objectsToMoves":[{
                          "objectPath":["8480f2a9d5c04353a258d262d5f23f3f"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"[[This.left]]",
                              "localVariables":{
                                "p6":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidget",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["eb55c113e9d04068ad2cd598296c1b0b"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"left"}]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"[[This.bottom]]",
                              "localVariables":{
                                "p6":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidget",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["eb55c113e9d04068ad2cd598296c1b0b"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"bottom"}]},
                            "options":{
}}}]}]}]},
            "onHide":{
              "description":"OnHide",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 r7 到 ([[This.left]],[[This.top]])",
                      "objectsToMoves":[{
                          "objectPath":["8480f2a9d5c04353a258d262d5f23f3f"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"[[This.left]]",
                              "localVariables":{
                                "p6":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidget",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["eb55c113e9d04068ad2cd598296c1b0b"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"left"}]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"[[This.top]]",
                              "localVariables":{
                                "p6":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidget",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["eb55c113e9d04068ad2cd598296c1b0b"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"top"}]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b6b5e22889784bd78e27d6c8df80ecbd",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"df6ed628797c4ae1b9148cff7d562c8c",
                  "label":"",
                  "parentDynamicPanel":"eb55c113e9d04068ad2cd598296c1b0b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF374D64},
                    "size":{
                      "width":200,
                      "height":40},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13416db2460a4cce8d7688754e326eb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eb55c113e9d04068ad2cd598296c1b0b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF374D64},
                        "size":{
                          "width":200,
                          "height":40},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/签约管理/u29.png"}},
{
                  "id":"194301557e954cbba14c9681fc533744",
                  "label":"",
                  "parentDynamicPanel":"eb55c113e9d04068ad2cd598296c1b0b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF374D64},
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":200,
                      "height":40},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"228688f48cd44d5d99e0714a0c4863c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eb55c113e9d04068ad2cd598296c1b0b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF374D64},
                        "location":{
                          "x":0,
                          "y":39},
                        "size":{
                          "width":200,
                          "height":40},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/签约管理/u29.png"}}]}]},
{
          "id":"8480f2a9d5c04353a258d262d5f23f3f",
          "label":"r7",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":652},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636cccc10cb743e8bbd8a79661f9ff9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":652},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证管理",
                      "target":{
                        "targetType":"page",
                        "url":"凭证管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r8 跟随",
                      "objectsToMoves":[{
                          "objectPath":["d989c86d64e045039bcd1a219bef54c0"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"d989c86d64e045039bcd1a219bef54c0",
          "label":"r8",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":702},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed2f2edaef24427a914f808dde45698c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":702},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r9 跟随",
                      "objectsToMoves":[{
                          "objectPath":["665305758a434a94b95f535cea3ad0ab"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"665305758a434a94b95f535cea3ad0ab",
          "label":"r9",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":752},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a7dcad0fb9e48258f155d93a6057d2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":752},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约管理",
                      "target":{
                        "targetType":"page",
                        "url":"签约管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r10 跟随",
                      "objectsToMoves":[{
                          "objectPath":["fec67349c913430c8bc99c033593b218"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"fec67349c913430c8bc99c033593b218",
          "label":"r10",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":802},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c034891a4024678a4c51f53d1799320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":802},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算管理（业务员）",
                      "target":{
                        "targetType":"page",
                        "url":"结算管理（业务员）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r11 跟随",
                      "objectsToMoves":[{
                          "objectPath":["41b890d2143e4a46a457aec816b5db78"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"41b890d2143e4a46a457aec816b5db78",
          "label":"r11",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":852},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e76e339cb54f87be5790cb35bfe19c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":852},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]},
{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 操作日志",
                      "target":{
                        "targetType":"page",
                        "url":"操作日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"397831f713c249e0b3f618e0a4a0e0da",
          "label":"t1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":80},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3faaf2ec4e67431c817331b06957d74f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"38d3c33c1f1a4bf185a9acaed7d476ca",
                  "label":"t1",
                  "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF374D64},
                    "size":{
                      "width":200,
                      "height":194},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF374D64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"387e9580738642eda7a8546c796ccfb5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF374D64},
                        "size":{
                          "width":200,
                          "height":194},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF374D64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/t1_u27.png"}},
{
                  "id":"4986f5025300468b98d961964d0e744b",
                  "label":"",
                  "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":85,
                      "y":102},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02a9887c3f1a4350931063a50d00fe54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":85,
                          "y":102},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c6f3105e81c640ee96fdf5609c423ae8",
                  "label":"",
                  "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":129},
                    "size":{
                      "width":44,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b070af991724aa49490c491103377a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":129},
                        "size":{
                          "width":44,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a19adb8300e3496cbf97b2637e34f3a3",
                  "label":"",
                  "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":42,
                      "y":155},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"70bd1b69141d4b568f9a0165a0efd41e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":42,
                          "y":155},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e0f25a08987146238fb56b938af502d6",
                  "label":"",
                  "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":118,
                      "y":155},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07eea1e53e31417a8caec342ce79cf5e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":118,
                          "y":155},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fd54d645302f40c5a93925bf4e0b9de9",
                  "label":"",
                  "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":74,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"642c83f9c7ac4de59cb1097436de2c84",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"397831f713c249e0b3f618e0a4a0e0da",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":74,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u37.png"}}]}]},
{
          "id":"6c6b92c521414b1bac5677ac4cfbd814",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":469,
              "y":90},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"014cfa896f504191a20174135778a239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":469,
                  "y":90},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约管理",
                      "target":{
                        "targetType":"page",
                        "url":"签约管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d317f8e01a64aaeb3a0195bf9d01e75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":1540,
              "y":91},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0482a2cd0d1d42f0a0999b77e46014ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":1540,
                  "y":91},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c318081fd1f94e839bb93c316fdb58ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":1490,
              "y":91},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4873789de8394b06935c85af635084af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":1490,
                  "y":91},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2284ab86672247e2bb7e4b4b86349b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":1440,
              "y":91},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b57831d4c02147079e1900ea03ef0f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":1440,
                  "y":91},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "44400dde669c41389f17926359b544f1":{
      "scriptId":"u0"},
    "0ca53800ff7c41f4b426fd3b4e3d6f95":{
      "scriptId":"u1"},
    "cb0e011043c445f7828bab67c885a544":{
      "scriptId":"u2"},
    "6fedadd6a06845aa884d948a34b689b9":{
      "scriptId":"u3"},
    "6cd08a7ea871427dabd729b6919a31ef":{
      "scriptId":"u4"},
    "91d05286874048dbbb19739d68d73e3f":{
      "scriptId":"u5"},
    "7e450e8c15084829968183409ee81240":{
      "scriptId":"u6"},
    "5a8d5be12f504697a91fe3d9ed960426":{
      "scriptId":"u7"},
    "76d1799bea314626a4efcc9b7e9958d0":{
      "scriptId":"u8"},
    "9360e160aa2542c699f06172ede62780":{
      "scriptId":"u9"},
    "ad32919471814d36b5d64fe8ba1deceb":{
      "scriptId":"u10"},
    "c5408d3c6eef410db5d0cd201999bdc9":{
      "scriptId":"u11"},
    "9a6c5bdad85746db988cdec15dd5fc05":{
      "scriptId":"u12"},
    "5778fc58d6844a3982b9305a6394bca0":{
      "scriptId":"u13"},
    "e42438b570964727818354995046dc8b":{
      "scriptId":"u14"},
    "fd78b1b3eb7d42a9b0449d6a1db9446c":{
      "scriptId":"u15"},
    "f7dbe999582b47159e2f9fe06b35dc3f":{
      "scriptId":"u16"},
    "bdea9a7b088b44e18e17afd0e53a6ec7":{
      "scriptId":"u17"},
    "c408649ff1af4d5196d591f3e68f18a6":{
      "scriptId":"u18"},
    "8e0e0d16c4a34dcfb059d0a3ee528734":{
      "scriptId":"u19"},
    "2f68843b82044df095b71dbf1d66782a":{
      "scriptId":"u20"},
    "107c89477cb142d4aa34de9a5f4cadca":{
      "scriptId":"u21"},
    "54ecce3cfaaf4ac7b634d33a32e63c19":{
      "scriptId":"u22"},
    "76ea0fcb05c24119960cd5b041379752":{
      "scriptId":"u23"},
    "75fdb691bb1b4b90abea3978b03bc722":{
      "scriptId":"u24"},
    "d7800141611f461ca81415438053b651":{
      "scriptId":"u25"},
    "8683110268a14c4b807de18e4549a5d2":{
      "scriptId":"u26"},
    "f9b10b306d10457cb7a9c9fcced667a5":{
      "scriptId":"u27"},
    "eb55c113e9d04068ad2cd598296c1b0b":{
      "scriptId":"u28"},
    "df6ed628797c4ae1b9148cff7d562c8c":{
      "scriptId":"u29"},
    "13416db2460a4cce8d7688754e326eb6":{
      "scriptId":"u30"},
    "194301557e954cbba14c9681fc533744":{
      "scriptId":"u31"},
    "228688f48cd44d5d99e0714a0c4863c2":{
      "scriptId":"u32"},
    "8480f2a9d5c04353a258d262d5f23f3f":{
      "scriptId":"u33"},
    "636cccc10cb743e8bbd8a79661f9ff9d":{
      "scriptId":"u34"},
    "d989c86d64e045039bcd1a219bef54c0":{
      "scriptId":"u35"},
    "ed2f2edaef24427a914f808dde45698c":{
      "scriptId":"u36"},
    "665305758a434a94b95f535cea3ad0ab":{
      "scriptId":"u37"},
    "6a7dcad0fb9e48258f155d93a6057d2d":{
      "scriptId":"u38"},
    "fec67349c913430c8bc99c033593b218":{
      "scriptId":"u39"},
    "4c034891a4024678a4c51f53d1799320":{
      "scriptId":"u40"},
    "41b890d2143e4a46a457aec816b5db78":{
      "scriptId":"u41"},
    "35e76e339cb54f87be5790cb35bfe19c":{
      "scriptId":"u42"},
    "397831f713c249e0b3f618e0a4a0e0da":{
      "scriptId":"u43"},
    "38d3c33c1f1a4bf185a9acaed7d476ca":{
      "scriptId":"u44"},
    "387e9580738642eda7a8546c796ccfb5":{
      "scriptId":"u45"},
    "4986f5025300468b98d961964d0e744b":{
      "scriptId":"u46"},
    "02a9887c3f1a4350931063a50d00fe54":{
      "scriptId":"u47"},
    "c6f3105e81c640ee96fdf5609c423ae8":{
      "scriptId":"u48"},
    "5b070af991724aa49490c491103377a9":{
      "scriptId":"u49"},
    "a19adb8300e3496cbf97b2637e34f3a3":{
      "scriptId":"u50"},
    "70bd1b69141d4b568f9a0165a0efd41e":{
      "scriptId":"u51"},
    "e0f25a08987146238fb56b938af502d6":{
      "scriptId":"u52"},
    "07eea1e53e31417a8caec342ce79cf5e":{
      "scriptId":"u53"},
    "fd54d645302f40c5a93925bf4e0b9de9":{
      "scriptId":"u54"},
    "642c83f9c7ac4de59cb1097436de2c84":{
      "scriptId":"u55"},
    "6c6b92c521414b1bac5677ac4cfbd814":{
      "scriptId":"u56"},
    "014cfa896f504191a20174135778a239":{
      "scriptId":"u57"},
    "1d317f8e01a64aaeb3a0195bf9d01e75":{
      "scriptId":"u58"},
    "0482a2cd0d1d42f0a0999b77e46014ea":{
      "scriptId":"u59"},
    "c318081fd1f94e839bb93c316fdb58ef":{
      "scriptId":"u60"},
    "4873789de8394b06935c85af635084af":{
      "scriptId":"u61"},
    "2284ab86672247e2bb7e4b4b86349b15":{
      "scriptId":"u62"},
    "b57831d4c02147079e1900ea03ef0f24":{
      "scriptId":"u63"}}});