$axure.loadCurrentPage({
  "url":"菜单列表（总览）.html",
  "generationDate":new Date(1516182746678.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"68efddc53b3a4cfd9929b71d677a6205",
    "type":"Axure:Page",
    "name":"菜单列表（总览）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d6db462e51b24fe8bc534fb9574e54e0",
          "label":"bg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":1880,
              "height":910}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f1896d48b83f46b48ac79924eb6dae95",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8e0c88d4ced24f0fa5c284850d163a35",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":1880,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ad27083d7f84fe2b75c544e3ce2cb38",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":1880,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u1.png"}},
{
                  "id":"8cb664db5a6d45b7bd0657593e0a0967",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA4AAB6},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":1880,
                      "height":2380},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7e16a1eb35d4d2db132e4668621bc34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA4AAB6},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":1880,
                          "height":2380},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u3.png"}},
{
                  "id":"9a7e7daebb0149308a5730ae2dd10be5",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":1489,
                      "y":17},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82b5d9a8dc3440c6a4d8974aec731439",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":1489,
                          "y":17},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"86cfb5117c084d7abcfc4e3a49e6b71d",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":1646,
                      "y":17},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8977a0612384d7fa3810eb8d507e4a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":1646,
                          "y":17},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"164f9958d7a448f1893a8cbbe891f5c2",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":746,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7c7f9052670445e905b0fcc810e3862",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":746,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"284e3416fe83451c8c17663944f2e63a",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":887,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41090ffae4aa49479976bbb2461d2a07",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":887,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1f093c0484034a1aadb7404400abcaec",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":1034,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0607914fb46542e09ee34521d07152b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":1034,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c80e7b1f25294a0c9ab1d48015388672",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":1164,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b86d741132ca44ef8915666b30fa655e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":1164,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f1101b4cc83471facf66d8efafaf245",
                  "label":"",
                  "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":1300,
                      "y":14},
                    "size":{
                      "width":88,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc12d050dc2d4577aa5be6d1993982be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6db462e51b24fe8bc534fb9574e54e0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":1300,
                          "y":14},
                        "size":{
                          "width":88,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"3c6a49579d2b4275966c8a491f35b591",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":6},
            "size":{
              "width":10,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表（总览）/u19_line.png"}},
{
          "id":"05cdcc5efab74402972a9e12170f5660",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":403,
              "y":15.5},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda7cbd4fbd44db4a953a21a3613dbb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":15.5},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02f94002f9aa46588a91becaf7dcf75a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":270,
              "y":11},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cf59bf46a454cefb289ea6ad87afff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":11},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e3fbbc5a5244fca96c53221e2df2b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":459,
              "y":80},
            "size":{
              "width":1131,
              "height":744}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee72011d01248598620a517820fa3d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":459,
                  "y":80},
                "size":{
                  "width":1131,
                  "height":744}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表（总览）/u24.png"}},
{
          "id":"a0a0330f5c6f4bae91744b4dbd3c2370",
          "label":"t1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":80},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"dc224d9c49994323975fc044243be141",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"18314101fe2843f88c92b0de37aa47be",
                  "label":"t1",
                  "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF374D64},
                    "size":{
                      "width":200,
                      "height":194},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF374D64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"adaa77faa18841178478dbc13fc69e8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF374D64},
                        "size":{
                          "width":200,
                          "height":194},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF374D64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/t1_u27.png"}},
{
                  "id":"d5a3da0952b64284842173621e324ced",
                  "label":"",
                  "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":85,
                      "y":102},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cc3f6a555224dc3b7f31b84d82f315e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":85,
                          "y":102},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fec81fdaf0e84b8489aec95247c795b2",
                  "label":"",
                  "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":129},
                    "size":{
                      "width":44,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"822e93a5801d4355b5ed4e527cce16d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":129},
                        "size":{
                          "width":44,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"94359cbd737a45efae2bce5c671f1e88",
                  "label":"",
                  "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":42,
                      "y":155},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63584ab0a7b34ec0ab62ff8fcfd83e62",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":42,
                          "y":155},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d543bc10678e4feb8075eb80913d66f3",
                  "label":"",
                  "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":118,
                      "y":155},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1c89bae07dc4f73986c4bf46b6bd6f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":118,
                          "y":155},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a61b8b627b024e769b3ef28d3cd67d61",
                  "label":"",
                  "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":74,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"518ee7564f3e4e4d89d94dc5e2503d19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0a0330f5c6f4bae91744b4dbd3c2370",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":74,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u37.png"}}]}]},
{
          "id":"b7f9828cba2f40d9bb26265000b064f4",
          "label":"r2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":274},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b38ddc0236bd4b618513d5caf73c35c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":274},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 权限管理（职位权限）",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理（职位权限）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"a98f903045144316ad9a8545b2a4e75b",
          "label":"r3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":324},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2109a889eeb44c959df504d3bd980d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":324},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 部门管理",
                      "target":{
                        "targetType":"page",
                        "url":"部门管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"57933f53c80b4fa0a29baec214ce4a83",
          "label":"r4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":374},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e209ab18ffc44edcb415ac1d16820ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":374},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 员工管理",
                      "target":{
                        "targetType":"page",
                        "url":"员工管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"eb9bc839763d4a88ae6f7392db9efefb",
          "label":"r5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":424},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d180c8e7c26d45418733af8b032face3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":424},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户管理",
                      "target":{
                        "targetType":"page",
                        "url":"客户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"0614868cff8c4b4cb5a1bb680977c6ea",
          "label":"r7",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":474},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdfcdd3e285e4ac8bde0ea16c8f64849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":474},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证管理",
                      "target":{
                        "targetType":"page",
                        "url":"凭证管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r8 跟随",
                      "objectsToMoves":[{
                          "objectPath":["b40899e29d894df2bba8f55aefdf870c"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"b40899e29d894df2bba8f55aefdf870c",
          "label":"r8",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":524},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0ae95fc9fca4007bdc82ccea4a58dba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":524},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r9 跟随",
                      "objectsToMoves":[{
                          "objectPath":["b715ed2ed2674bf3b96ac9a8e14d0a9e"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"b715ed2ed2674bf3b96ac9a8e14d0a9e",
          "label":"r9",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":574},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a727929a3b4e8ab6a0127868aceb73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":574},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约管理",
                      "target":{
                        "targetType":"page",
                        "url":"签约管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r10 跟随",
                      "objectsToMoves":[{
                          "objectPath":["7d08a00d9f7042a4a69eafd017ae4d2b"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"7d08a00d9f7042a4a69eafd017ae4d2b",
          "label":"r10",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":624},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e1bd9203860406da2c284e456e32ad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":624},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算管理（业务员）",
                      "target":{
                        "targetType":"page",
                        "url":"结算管理（业务员）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r11 跟随",
                      "objectsToMoves":[{
                          "objectPath":["9002ca347e2e4b53a35dbc80d0e8d674"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"9002ca347e2e4b53a35dbc80d0e8d674",
          "label":"r11",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":674},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"782720f7710b4ed8895a8e7eb8fd8331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":674},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 操作日志",
                      "target":{
                        "targetType":"page",
                        "url":"操作日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r12 跟随",
                      "objectsToMoves":[{
                          "objectPath":["5b6f5449974541c89b51bf246dbd2153"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"5b6f5449974541c89b51bf246dbd2153",
          "label":"r12",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":724},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64856a7cdd604d7e9067efb357d25450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":724},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个个人收益账单",
                      "target":{
                        "targetType":"page",
                        "url":"单个个人收益账单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d6db462e51b24fe8bc534fb9574e54e0":{
      "scriptId":"u0"},
    "8e0c88d4ced24f0fa5c284850d163a35":{
      "scriptId":"u1"},
    "0ad27083d7f84fe2b75c544e3ce2cb38":{
      "scriptId":"u2"},
    "8cb664db5a6d45b7bd0657593e0a0967":{
      "scriptId":"u3"},
    "d7e16a1eb35d4d2db132e4668621bc34":{
      "scriptId":"u4"},
    "9a7e7daebb0149308a5730ae2dd10be5":{
      "scriptId":"u5"},
    "82b5d9a8dc3440c6a4d8974aec731439":{
      "scriptId":"u6"},
    "86cfb5117c084d7abcfc4e3a49e6b71d":{
      "scriptId":"u7"},
    "f8977a0612384d7fa3810eb8d507e4a2":{
      "scriptId":"u8"},
    "164f9958d7a448f1893a8cbbe891f5c2":{
      "scriptId":"u9"},
    "a7c7f9052670445e905b0fcc810e3862":{
      "scriptId":"u10"},
    "284e3416fe83451c8c17663944f2e63a":{
      "scriptId":"u11"},
    "41090ffae4aa49479976bbb2461d2a07":{
      "scriptId":"u12"},
    "1f093c0484034a1aadb7404400abcaec":{
      "scriptId":"u13"},
    "0607914fb46542e09ee34521d07152b6":{
      "scriptId":"u14"},
    "c80e7b1f25294a0c9ab1d48015388672":{
      "scriptId":"u15"},
    "b86d741132ca44ef8915666b30fa655e":{
      "scriptId":"u16"},
    "0f1101b4cc83471facf66d8efafaf245":{
      "scriptId":"u17"},
    "dc12d050dc2d4577aa5be6d1993982be":{
      "scriptId":"u18"},
    "3c6a49579d2b4275966c8a491f35b591":{
      "scriptId":"u19"},
    "05cdcc5efab74402972a9e12170f5660":{
      "scriptId":"u20"},
    "dda7cbd4fbd44db4a953a21a3613dbb2":{
      "scriptId":"u21"},
    "02f94002f9aa46588a91becaf7dcf75a":{
      "scriptId":"u22"},
    "5cf59bf46a454cefb289ea6ad87afff0":{
      "scriptId":"u23"},
    "37e3fbbc5a5244fca96c53221e2df2b4":{
      "scriptId":"u24"},
    "5ee72011d01248598620a517820fa3d6":{
      "scriptId":"u25"},
    "a0a0330f5c6f4bae91744b4dbd3c2370":{
      "scriptId":"u26"},
    "18314101fe2843f88c92b0de37aa47be":{
      "scriptId":"u27"},
    "adaa77faa18841178478dbc13fc69e8e":{
      "scriptId":"u28"},
    "d5a3da0952b64284842173621e324ced":{
      "scriptId":"u29"},
    "6cc3f6a555224dc3b7f31b84d82f315e":{
      "scriptId":"u30"},
    "fec81fdaf0e84b8489aec95247c795b2":{
      "scriptId":"u31"},
    "822e93a5801d4355b5ed4e527cce16d5":{
      "scriptId":"u32"},
    "94359cbd737a45efae2bce5c671f1e88":{
      "scriptId":"u33"},
    "63584ab0a7b34ec0ab62ff8fcfd83e62":{
      "scriptId":"u34"},
    "d543bc10678e4feb8075eb80913d66f3":{
      "scriptId":"u35"},
    "b1c89bae07dc4f73986c4bf46b6bd6f0":{
      "scriptId":"u36"},
    "a61b8b627b024e769b3ef28d3cd67d61":{
      "scriptId":"u37"},
    "518ee7564f3e4e4d89d94dc5e2503d19":{
      "scriptId":"u38"},
    "b7f9828cba2f40d9bb26265000b064f4":{
      "scriptId":"u39"},
    "b38ddc0236bd4b618513d5caf73c35c4":{
      "scriptId":"u40"},
    "a98f903045144316ad9a8545b2a4e75b":{
      "scriptId":"u41"},
    "2109a889eeb44c959df504d3bd980d55":{
      "scriptId":"u42"},
    "57933f53c80b4fa0a29baec214ce4a83":{
      "scriptId":"u43"},
    "e209ab18ffc44edcb415ac1d16820ecb":{
      "scriptId":"u44"},
    "eb9bc839763d4a88ae6f7392db9efefb":{
      "scriptId":"u45"},
    "d180c8e7c26d45418733af8b032face3":{
      "scriptId":"u46"},
    "0614868cff8c4b4cb5a1bb680977c6ea":{
      "scriptId":"u47"},
    "bdfcdd3e285e4ac8bde0ea16c8f64849":{
      "scriptId":"u48"},
    "b40899e29d894df2bba8f55aefdf870c":{
      "scriptId":"u49"},
    "d0ae95fc9fca4007bdc82ccea4a58dba":{
      "scriptId":"u50"},
    "b715ed2ed2674bf3b96ac9a8e14d0a9e":{
      "scriptId":"u51"},
    "42a727929a3b4e8ab6a0127868aceb73":{
      "scriptId":"u52"},
    "7d08a00d9f7042a4a69eafd017ae4d2b":{
      "scriptId":"u53"},
    "8e1bd9203860406da2c284e456e32ad8":{
      "scriptId":"u54"},
    "9002ca347e2e4b53a35dbc80d0e8d674":{
      "scriptId":"u55"},
    "782720f7710b4ed8895a8e7eb8fd8331":{
      "scriptId":"u56"},
    "5b6f5449974541c89b51bf246dbd2153":{
      "scriptId":"u57"},
    "64856a7cdd604d7e9067efb357d25450":{
      "scriptId":"u58"}}});