$axure.loadCurrentPage({
  "url":"权限管理（职位权限）.html",
  "generationDate":new Date(1516182747504.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"d4989284cb98487aac53fa7c3407a018",
    "type":"Axure:Page",
    "name":"权限管理（职位权限）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48e5583a043142df949c4cc7ac3c3eaf",
          "label":"bg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":1880,
              "height":1130}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a8773f84f7394c57ac98fb2d2714d8d0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"949cc705dc54425c9da51c04d42f959a",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":1880,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebbcd2e49edb49b798d55434add4d6ff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":1880,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u1.png"}},
{
                  "id":"6743fc4f7bd346e3bc0ecc7e274d0d64",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA4AAB6},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":1880,
                      "height":2380},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d9eea2140fd47e2a6b9d594ab92ad6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA4AAB6},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":1880,
                          "height":2380},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u3.png"}},
{
                  "id":"765d8f104f9c46718497abe5101f76e8",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":1489,
                      "y":17},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1daaf0c253149be98062a4bec24ecc5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":1489,
                          "y":17},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08ef02060a7842aa80223dd374f3c710",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":1646,
                      "y":17},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85c5bc148f7248e786a6bd046ef2167a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":1646,
                          "y":17},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"913d57f911334ed7b1baef849cb17a04",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":746,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7760dfeb54ce449fae2b7561524b9ac6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":746,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2edb517a88c84c63bd0ed67edb248e94",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":887,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e445f8dfde1a4f54adcfc7b6da5981d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":887,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f531dd92859145bc92a078fd48900288",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":1034,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ac76bac53c44c5ea546fa83fa9df0f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":1034,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1d2f253fd2c44141b052f7cbf4cc6abd",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":1164,
                      "y":14},
                    "size":{
                      "width":106,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e50c080546e94a7eaa4829ff1ac8c94a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":1164,
                          "y":14},
                        "size":{
                          "width":106,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"343d802efcfc4c0abcb88e08d722dbb3",
                  "label":"",
                  "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "location":{
                      "x":1300,
                      "y":14},
                    "size":{
                      "width":88,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7e7441eaec04ce5b04d7b37f43821f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"48e5583a043142df949c4cc7ac3c3eaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "location":{
                          "x":1300,
                          "y":14},
                        "size":{
                          "width":88,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"0af304b77b2c4d4e9c49cbdbfc59e454",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":6},
            "size":{
              "width":10,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表（总览）/u19_line.png"}},
{
          "id":"09ad7b9b244e436ead6bb37f90aa93ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":403,
              "y":16},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c44284f6026b484397bb4a88e472cf5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":16},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9070ec5df53d43a2ab0e3b64c9a1b6f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":459,
              "y":80},
            "size":{
              "width":1131,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b9822a2213404eb76492b7e3acb420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":459,
                  "y":80},
                "size":{
                  "width":1131,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工编辑个人资料/u24.png"}},
{
          "id":"0c8b70424bec4546b442ce666d65fabf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":270,
              "y":11},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d6dafb552b40c1b74db2f5db748324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":11},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"880df5a9491848ccac5b0181fe95e0fb",
          "label":"t1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":80},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"176bda857df14c5db485a21a180d5074",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"87a2ddc6b15e4bd09849ca71c8eb5279",
                  "label":"t1",
                  "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF374D64},
                    "size":{
                      "width":200,
                      "height":194},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF374D64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32424522cbb84b619267918fdf1b29cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF374D64},
                        "size":{
                          "width":200,
                          "height":194},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF374D64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/t1_u27.png"}},
{
                  "id":"55031906bedf43a697715a1357f9dfeb",
                  "label":"",
                  "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":85,
                      "y":102},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9afdf5bfb8745a0a7150a092961bcb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":85,
                          "y":102},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dfa95aaea32e44f9bd9ea5714b880736",
                  "label":"",
                  "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":129},
                    "size":{
                      "width":44,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc52eea349734447add98ae0bab68fb9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":129},
                        "size":{
                          "width":44,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d0aa8b7cd8d84fb58388b4dbd3101993",
                  "label":"",
                  "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":42,
                      "y":155},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c707eb9da724d8cb52d2eb25b2e1b31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":42,
                          "y":155},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"50a6813da44d4f038c3a813f4edbb152",
                  "label":"",
                  "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":118,
                      "y":155},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6f8f40deb69406b9119e037ecb954af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":118,
                          "y":155},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"61b1b15d04824bce9fea29147d95dbc0",
                  "label":"",
                  "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":74,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"501d62abb33d482b893e58e7f5bf26ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"880df5a9491848ccac5b0181fe95e0fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":74,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/权限管理（职位权限）/u37.png"}}]}]},
{
          "id":"5177ad55cb1d4033973196ad20d8d39b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":502,
              "y":160},
            "size":{
              "width":1057,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfcd70df9f9446189dc5c0179f163670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":502,
                  "y":160},
                "size":{
                  "width":1057,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限管理（职位权限）/u39.png"}},
{
          "id":"707d30d1dc2f43e4a73012dfd1578956",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":624,
              "y":171},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f10230ca55e34fdbbadb24f21dad7b0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":624,
                  "y":171},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec65d3bb1c0a424f9c68ec31384293b1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":198},
            "size":{
              "width":10,
              "height":322},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u43_line.png"}},
{
          "id":"52e86649036d4a12bdf5db11dc8c74dc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":234},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"99e1c65543a1409ca493790cec5f07aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":1038,
              "y":171},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"779bfdd2896d446b968b039de2030c4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":1038,
                  "y":171},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a2387cda1284ac78d9c5af480068cab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":274},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"97c3e7e5c2ca40e4be5fd79d1a2f19d2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":160},
            "size":{
              "width":10,
              "height":360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u48_line.png"}},
{
          "id":"63289d13c2824afbad4efc3a562bb5cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":314},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"be8a06d5c223489bb6750443fca872b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":354},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"01275b82ec3341a881dae98dc9a03db5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":394},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"4bff297c34b04f3db644444576b3e504",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":434},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"8238f127ec194f92bcfccba298e4d1d2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1554,
              "y":198},
            "size":{
              "width":10,
              "height":322},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u43_line.png"}},
{
          "id":"e00c90b77cd34e70b8ef6f820cbec529",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":210},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96ae38746894700a98c009d5fea748a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":210},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b34b9bb2de34f09843e152c8990444f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":254},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"200d08d5ced045108672febe9a14b122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":254},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c4c79e58b0a4cc4aa386781b045b0e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":294},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52bac7097b9b44d1b76502ca010862be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":294},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f4b8ab3a7b24bec883ea363d0ada046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":331},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ff731f68c6c41f1942e38e23dadbd6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":331},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"202fe6e7b409442f99a22835e3e3c22e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":374},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49144a5add14551b7419c46174c5b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":374},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20762d894fa044ee868ad8a5d735fa22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":412},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0849c83d2fc467eb32833fc052a92bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":412},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"190da4cc588e4d98b724b15a48831fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":794,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a211e02ce3884a1197689a7a5bdd2740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":794,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92aa5429ded94483ab41bb70249279e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":874,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecf24e72a1424c3e964daa4f7efad50e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":874,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"404aaa62a3c241aa92b4c8477584d586",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":962,
              "y":210},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478e68ef964944268a978a25c1931bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":962,
                  "y":210},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a6aa1f57fb24691b71d0320650a608b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":1068,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bb84e5dcc554c6fa48971561dbf4ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":1068,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b9c92a275cf47ad8dc176416565b45e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":1158,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d000d678cb14015b1b93ea1811574b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":1158,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a4fdc6f9d6c40b09bb691f29642217e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":1244,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ee3ba2ea24495dbc4b5098b75b06d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":1244,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2307c237c054ee7a80c85ec32a11bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":498,
              "y":110},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f22ddcdb52d470c81f94811ad59bbce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":498,
                  "y":110},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47ad7bba73b34b1cb7fe9ec9faf7eb85",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":136},
            "size":{
              "width":1061,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u80_line.png"}},
{
          "id":"26fe45e0ae944f71a2f41e2833b5cdcb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":473},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"9a3aac0996454e158317a0c3036c882a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":451},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0141dfeda142414aaa722baa280ec6c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":451},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60eab2dc482c44038dce81c4a5322a6d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":515},
            "size":{
              "width":1056,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限管理（职位权限）/u44_line.png"}},
{
          "id":"e8ffa5c724164a718316abb6b02d47a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":616,
              "y":493},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce74d6e49bb9403f88fd399a7585b602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":616,
                  "y":493},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e35cdcd4e90d45e09a6f9adac8c8315c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":784,
              "y":493},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73cf59cba1b94194ac3f16cceba3a1cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":784,
                  "y":493},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43c3a1d843504bfab1d2b42532085339",
          "label":"r2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":274},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6845f3c5f4c4bff93e0a60ecf21945b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":274},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 权限管理（职位权限）",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理（职位权限）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"c693972c233441fd81ae07dc2396b99d",
          "label":"r3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":324},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"449262cc612d4e9d811aee33ad9f294e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":324},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 部门管理",
                      "target":{
                        "targetType":"page",
                        "url":"部门管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"d5e39e57c1194028a0b74b33802246ec",
          "label":"r4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":374},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"def4c97d3f5643e494f0a7567ba8c633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":374},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 员工管理",
                      "target":{
                        "targetType":"page",
                        "url":"员工管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"e2ec0439508546ab8cd105f674e458ce",
          "label":"r5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":424},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0af1f0d3675455596cbd62f5025e623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":424},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户管理",
                      "target":{
                        "targetType":"page",
                        "url":"客户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"ce5d00ebdf7248c690c80e1ec9e7a688",
          "label":"r7",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":474},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183286519fdc499499f3c46a88c83828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":474},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证管理",
                      "target":{
                        "targetType":"page",
                        "url":"凭证管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r8 跟随",
                      "objectsToMoves":[{
                          "objectPath":["b22013eb16fb456eac406eed2dd9b6ae"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"b22013eb16fb456eac406eed2dd9b6ae",
          "label":"r8",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":524},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28cde2c6535246b586097a490cc1e1c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":524},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r9 跟随",
                      "objectsToMoves":[{
                          "objectPath":["cb7c4592ad6946e4a190f60efee0ee7e"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"cb7c4592ad6946e4a190f60efee0ee7e",
          "label":"r9",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":574},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbb4ce8ba8ee424ab4e63ab8349d3b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":574},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约管理",
                      "target":{
                        "targetType":"page",
                        "url":"签约管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r10 跟随",
                      "objectsToMoves":[{
                          "objectPath":["a00da471d1b34c3eb0c8b9f398047284"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"a00da471d1b34c3eb0c8b9f398047284",
          "label":"r10",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":624},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc2aa92e1e244e6793fc8e8478e749dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":624},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算管理（业务员）",
                      "target":{
                        "targetType":"page",
                        "url":"结算管理（业务员）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r11 跟随",
                      "objectsToMoves":[{
                          "objectPath":["193102ea45a84aaea20c2d598cc54bd5"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"193102ea45a84aaea20c2d598cc54bd5",
          "label":"r11",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":674},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4012e8e15d2b45fdaa9d73a46ca311b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":674},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 操作日志",
                      "target":{
                        "targetType":"page",
                        "url":"操作日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r12 跟随",
                      "objectsToMoves":[{
                          "objectPath":["9e10223530914c6bb86202f6148d1f94"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"9e10223530914c6bb86202f6148d1f94",
          "label":"r12",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":724},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e239df6d882e4ddd97b976efee5d4b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":724},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个个人收益账单",
                      "target":{
                        "targetType":"page",
                        "url":"单个个人收益账单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "48e5583a043142df949c4cc7ac3c3eaf":{
      "scriptId":"u0"},
    "949cc705dc54425c9da51c04d42f959a":{
      "scriptId":"u1"},
    "ebbcd2e49edb49b798d55434add4d6ff":{
      "scriptId":"u2"},
    "6743fc4f7bd346e3bc0ecc7e274d0d64":{
      "scriptId":"u3"},
    "1d9eea2140fd47e2a6b9d594ab92ad6a":{
      "scriptId":"u4"},
    "765d8f104f9c46718497abe5101f76e8":{
      "scriptId":"u5"},
    "b1daaf0c253149be98062a4bec24ecc5":{
      "scriptId":"u6"},
    "08ef02060a7842aa80223dd374f3c710":{
      "scriptId":"u7"},
    "85c5bc148f7248e786a6bd046ef2167a":{
      "scriptId":"u8"},
    "913d57f911334ed7b1baef849cb17a04":{
      "scriptId":"u9"},
    "7760dfeb54ce449fae2b7561524b9ac6":{
      "scriptId":"u10"},
    "2edb517a88c84c63bd0ed67edb248e94":{
      "scriptId":"u11"},
    "e445f8dfde1a4f54adcfc7b6da5981d7":{
      "scriptId":"u12"},
    "f531dd92859145bc92a078fd48900288":{
      "scriptId":"u13"},
    "2ac76bac53c44c5ea546fa83fa9df0f8":{
      "scriptId":"u14"},
    "1d2f253fd2c44141b052f7cbf4cc6abd":{
      "scriptId":"u15"},
    "e50c080546e94a7eaa4829ff1ac8c94a":{
      "scriptId":"u16"},
    "343d802efcfc4c0abcb88e08d722dbb3":{
      "scriptId":"u17"},
    "d7e7441eaec04ce5b04d7b37f43821f6":{
      "scriptId":"u18"},
    "0af304b77b2c4d4e9c49cbdbfc59e454":{
      "scriptId":"u19"},
    "09ad7b9b244e436ead6bb37f90aa93ba":{
      "scriptId":"u20"},
    "c44284f6026b484397bb4a88e472cf5b":{
      "scriptId":"u21"},
    "9070ec5df53d43a2ab0e3b64c9a1b6f5":{
      "scriptId":"u22"},
    "28b9822a2213404eb76492b7e3acb420":{
      "scriptId":"u23"},
    "0c8b70424bec4546b442ce666d65fabf":{
      "scriptId":"u24"},
    "50d6dafb552b40c1b74db2f5db748324":{
      "scriptId":"u25"},
    "880df5a9491848ccac5b0181fe95e0fb":{
      "scriptId":"u26"},
    "87a2ddc6b15e4bd09849ca71c8eb5279":{
      "scriptId":"u27"},
    "32424522cbb84b619267918fdf1b29cd":{
      "scriptId":"u28"},
    "55031906bedf43a697715a1357f9dfeb":{
      "scriptId":"u29"},
    "e9afdf5bfb8745a0a7150a092961bcb6":{
      "scriptId":"u30"},
    "dfa95aaea32e44f9bd9ea5714b880736":{
      "scriptId":"u31"},
    "fc52eea349734447add98ae0bab68fb9":{
      "scriptId":"u32"},
    "d0aa8b7cd8d84fb58388b4dbd3101993":{
      "scriptId":"u33"},
    "2c707eb9da724d8cb52d2eb25b2e1b31":{
      "scriptId":"u34"},
    "50a6813da44d4f038c3a813f4edbb152":{
      "scriptId":"u35"},
    "a6f8f40deb69406b9119e037ecb954af":{
      "scriptId":"u36"},
    "61b1b15d04824bce9fea29147d95dbc0":{
      "scriptId":"u37"},
    "501d62abb33d482b893e58e7f5bf26ca":{
      "scriptId":"u38"},
    "5177ad55cb1d4033973196ad20d8d39b":{
      "scriptId":"u39"},
    "dfcd70df9f9446189dc5c0179f163670":{
      "scriptId":"u40"},
    "707d30d1dc2f43e4a73012dfd1578956":{
      "scriptId":"u41"},
    "f10230ca55e34fdbbadb24f21dad7b0c":{
      "scriptId":"u42"},
    "ec65d3bb1c0a424f9c68ec31384293b1":{
      "scriptId":"u43"},
    "52e86649036d4a12bdf5db11dc8c74dc":{
      "scriptId":"u44"},
    "99e1c65543a1409ca493790cec5f07aa":{
      "scriptId":"u45"},
    "779bfdd2896d446b968b039de2030c4d":{
      "scriptId":"u46"},
    "0a2387cda1284ac78d9c5af480068cab":{
      "scriptId":"u47"},
    "97c3e7e5c2ca40e4be5fd79d1a2f19d2":{
      "scriptId":"u48"},
    "63289d13c2824afbad4efc3a562bb5cf":{
      "scriptId":"u49"},
    "be8a06d5c223489bb6750443fca872b2":{
      "scriptId":"u50"},
    "01275b82ec3341a881dae98dc9a03db5":{
      "scriptId":"u51"},
    "4bff297c34b04f3db644444576b3e504":{
      "scriptId":"u52"},
    "8238f127ec194f92bcfccba298e4d1d2":{
      "scriptId":"u53"},
    "e00c90b77cd34e70b8ef6f820cbec529":{
      "scriptId":"u54"},
    "e96ae38746894700a98c009d5fea748a":{
      "scriptId":"u55"},
    "2b34b9bb2de34f09843e152c8990444f":{
      "scriptId":"u56"},
    "200d08d5ced045108672febe9a14b122":{
      "scriptId":"u57"},
    "2c4c79e58b0a4cc4aa386781b045b0e6":{
      "scriptId":"u58"},
    "52bac7097b9b44d1b76502ca010862be":{
      "scriptId":"u59"},
    "3f4b8ab3a7b24bec883ea363d0ada046":{
      "scriptId":"u60"},
    "9ff731f68c6c41f1942e38e23dadbd6f":{
      "scriptId":"u61"},
    "202fe6e7b409442f99a22835e3e3c22e":{
      "scriptId":"u62"},
    "a49144a5add14551b7419c46174c5b28":{
      "scriptId":"u63"},
    "20762d894fa044ee868ad8a5d735fa22":{
      "scriptId":"u64"},
    "e0849c83d2fc467eb32833fc052a92bf":{
      "scriptId":"u65"},
    "190da4cc588e4d98b724b15a48831fbe":{
      "scriptId":"u66"},
    "a211e02ce3884a1197689a7a5bdd2740":{
      "scriptId":"u67"},
    "92aa5429ded94483ab41bb70249279e0":{
      "scriptId":"u68"},
    "ecf24e72a1424c3e964daa4f7efad50e":{
      "scriptId":"u69"},
    "404aaa62a3c241aa92b4c8477584d586":{
      "scriptId":"u70"},
    "478e68ef964944268a978a25c1931bfe":{
      "scriptId":"u71"},
    "6a6aa1f57fb24691b71d0320650a608b":{
      "scriptId":"u72"},
    "5bb84e5dcc554c6fa48971561dbf4ad1":{
      "scriptId":"u73"},
    "3b9c92a275cf47ad8dc176416565b45e":{
      "scriptId":"u74"},
    "6d000d678cb14015b1b93ea1811574b0":{
      "scriptId":"u75"},
    "9a4fdc6f9d6c40b09bb691f29642217e":{
      "scriptId":"u76"},
    "81ee3ba2ea24495dbc4b5098b75b06d0":{
      "scriptId":"u77"},
    "d2307c237c054ee7a80c85ec32a11bb5":{
      "scriptId":"u78"},
    "9f22ddcdb52d470c81f94811ad59bbce":{
      "scriptId":"u79"},
    "47ad7bba73b34b1cb7fe9ec9faf7eb85":{
      "scriptId":"u80"},
    "26fe45e0ae944f71a2f41e2833b5cdcb":{
      "scriptId":"u81"},
    "9a3aac0996454e158317a0c3036c882a":{
      "scriptId":"u82"},
    "0141dfeda142414aaa722baa280ec6c0":{
      "scriptId":"u83"},
    "60eab2dc482c44038dce81c4a5322a6d":{
      "scriptId":"u84"},
    "e8ffa5c724164a718316abb6b02d47a4":{
      "scriptId":"u85"},
    "ce74d6e49bb9403f88fd399a7585b602":{
      "scriptId":"u86"},
    "e35cdcd4e90d45e09a6f9adac8c8315c":{
      "scriptId":"u87"},
    "73cf59cba1b94194ac3f16cceba3a1cf":{
      "scriptId":"u88"},
    "43c3a1d843504bfab1d2b42532085339":{
      "scriptId":"u89"},
    "f6845f3c5f4c4bff93e0a60ecf21945b":{
      "scriptId":"u90"},
    "c693972c233441fd81ae07dc2396b99d":{
      "scriptId":"u91"},
    "449262cc612d4e9d811aee33ad9f294e":{
      "scriptId":"u92"},
    "d5e39e57c1194028a0b74b33802246ec":{
      "scriptId":"u93"},
    "def4c97d3f5643e494f0a7567ba8c633":{
      "scriptId":"u94"},
    "e2ec0439508546ab8cd105f674e458ce":{
      "scriptId":"u95"},
    "e0af1f0d3675455596cbd62f5025e623":{
      "scriptId":"u96"},
    "ce5d00ebdf7248c690c80e1ec9e7a688":{
      "scriptId":"u97"},
    "183286519fdc499499f3c46a88c83828":{
      "scriptId":"u98"},
    "b22013eb16fb456eac406eed2dd9b6ae":{
      "scriptId":"u99"},
    "28cde2c6535246b586097a490cc1e1c5":{
      "scriptId":"u100"},
    "cb7c4592ad6946e4a190f60efee0ee7e":{
      "scriptId":"u101"},
    "fbb4ce8ba8ee424ab4e63ab8349d3b51":{
      "scriptId":"u102"},
    "a00da471d1b34c3eb0c8b9f398047284":{
      "scriptId":"u103"},
    "cc2aa92e1e244e6793fc8e8478e749dd":{
      "scriptId":"u104"},
    "193102ea45a84aaea20c2d598cc54bd5":{
      "scriptId":"u105"},
    "4012e8e15d2b45fdaa9d73a46ca311b6":{
      "scriptId":"u106"},
    "9e10223530914c6bb86202f6148d1f94":{
      "scriptId":"u107"},
    "e239df6d882e4ddd97b976efee5d4b05":{
      "scriptId":"u108"}}});