$axure.loadCurrentPage({
  "url":"产品管理.html",
  "generationDate":new Date(1516182757421.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"481c286cc3654d50aae7495d343f453c",
    "type":"Axure:Page",
    "name":"产品管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f28d7d73406c481c8de38fdab7ac68d4",
          "label":"bg",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":1880,
              "height":1110}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a7cde7372711475caf274eba8ec5905a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d27ea72b513144c58c175917ba67b4f0",
                  "label":"",
                  "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":1880,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"676d4df35c6940eb9bf0f2b48c5496a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":1880,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u1.png"}},
{
                  "id":"14f4f97e9cfa49e18b1afd31ac7744df",
                  "label":"",
                  "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA4AAB6},
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":1880,
                      "height":2380},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24c377bff6bd4afebed3c085c17bb9fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA4AAB6},
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":1880,
                          "height":2380},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u3.png"}},
{
                  "id":"e31c1782753b45b0820099a7afb28882",
                  "label":"",
                  "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":1489,
                      "y":17},
                    "size":{
                      "width":101,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e3632fb22f04355ab9e8dc0dabb1c9b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":1489,
                          "y":17},
                        "size":{
                          "width":101,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b8340cb792ca41fba123060a59aedaaf",
                  "label":"",
                  "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":1646,
                      "y":17},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e8f9cbbb39546c9ac54df258457d3b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f28d7d73406c481c8de38fdab7ac68d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":1646,
                          "y":17},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"01e18616e8b240dc835bb0d57daaae1c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":6},
            "size":{
              "width":10,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表（总览）/u19_line.png"}},
{
          "id":"538fe696583b4c138580ee7df0c2d821",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":403,
              "y":16},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf947a2ab0474f398dff2ddc49f74849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":403,
                  "y":16},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22a1619bb1174a8880092881f5422b69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":459,
              "y":80},
            "size":{
              "width":1131,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d036c0f294de4af59f14ec09ae00f363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":459,
                  "y":80},
                "size":{
                  "width":1131,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/员工编辑个人资料/u24.png"}},
{
          "id":"1c0c775e39944a38879a8f345b889ca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":270,
              "y":11},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a9624f2a0604a588b219708f59eac61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":11},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36980cb5e7e74963912b1b83faca8bd6",
          "label":"t1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":80},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7622144f47ac48cdb6f2a48ef2c7f492",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bfff0898f03e4c2fae6113aba4da7b2a",
                  "label":"t1",
                  "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF374D64},
                    "size":{
                      "width":200,
                      "height":194},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF374D64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5436d03ff2bc45399675e9ab6ced4a2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF374D64},
                        "size":{
                          "width":200,
                          "height":194},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF374D64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/t1_u27.png"}},
{
                  "id":"98f8697dd5564fc69dba59e23c506150",
                  "label":"",
                  "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":85,
                      "y":102},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b7c54e7aecc4770b0105c4575bbb459",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":85,
                          "y":102},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f2fa7825ad2468eb31168ab732cf823",
                  "label":"",
                  "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":129},
                    "size":{
                      "width":44,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c2f0144467a4bb5889c4a64c88ffbf5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":129},
                        "size":{
                          "width":44,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fde509fcc7bf4a808bf030a40ad246a9",
                  "label":"",
                  "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":42,
                      "y":155},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6a060b0c35a4901807cbf577a23fa07",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":42,
                          "y":155},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ce7023f4433f4886a8b5d5dd0d8d0978",
                  "label":"",
                  "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":118,
                      "y":155},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e68c86e8bc7497e804565604e2518f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":118,
                          "y":155},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5215ce0bd3df4d8695d5369e4e743052",
                  "label":"",
                  "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":74,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac5c61b031ea4443a28262143f548295",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"36980cb5e7e74963912b1b83faca8bd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":74,
                          "y":30},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/菜单列表（总览）/u37.png"}}]}]},
{
          "id":"ddf1811f10b84a378f692c317f184c39",
          "label":"r1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":274},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca04379e7826405d8d0be38bda4c2844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":274},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品管理/r1_u29.png"}},
{
          "id":"ac46afad82a84ed2913fcbc2f96debb1",
          "label":"r2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":324},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e3ced70a0c94dd69076c6eb395c0529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":324},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 权限管理（职位权限）",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理（职位权限）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"20251e4ea59743e7ba164a4a44b3bcbe",
          "label":"r3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":374},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f50422941d64f3da28e4099b9fae32b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":374},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 部门管理",
                      "target":{
                        "targetType":"page",
                        "url":"部门管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"0c6c844b2c7042b9944b7fcb8696b56d",
          "label":"r4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":424},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3d7086365104e12901cfbe3401208ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":424},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 员工管理",
                      "target":{
                        "targetType":"page",
                        "url":"员工管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"c9613b45abfc4edfb3573568213de8ab",
          "label":"r5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":474},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19cfca2a551f44b99fdedba0e11e1e29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":474},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户管理",
                      "target":{
                        "targetType":"page",
                        "url":"客户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"540b9ed9c9ff4bd099547c07d6a5e5af",
          "label":"r6",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":524},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f83a09ffecc540f6afec4f7a1f36f60a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":524},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"12178199e32d47d086ca90013fadd50a",
          "label":"r7",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":574},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed62e39c52a644dc872eccf7b32b3b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":574},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证管理",
                      "target":{
                        "targetType":"page",
                        "url":"凭证管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r8 跟随",
                      "objectsToMoves":[{
                          "objectPath":["a8ac5de440ac434aa6adabe96f3d220c"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"a8ac5de440ac434aa6adabe96f3d220c",
          "label":"r8",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":624},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214683a784a94d3c9ca3d8bd5c03f674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":624},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r9 跟随",
                      "objectsToMoves":[{
                          "objectPath":["827aa1b15d1c4151b69fa55c163d1e7e"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"827aa1b15d1c4151b69fa55c163d1e7e",
          "label":"r9",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":674},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda2abf721dc45dfb98847887e98e520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":674},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约管理",
                      "target":{
                        "targetType":"page",
                        "url":"签约管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r10 跟随",
                      "objectsToMoves":[{
                          "objectPath":["b214cb2a1ef04fb3999244cf6fde0c49"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"b214cb2a1ef04fb3999244cf6fde0c49",
          "label":"r10",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":724},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa96b3ee67845b783e5a9acfb59fa26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":724},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算管理（业务员）",
                      "target":{
                        "targetType":"page",
                        "url":"结算管理（业务员）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r11 跟随",
                      "objectsToMoves":[{
                          "objectPath":["b2901ef22c71453b9fd6e13573ee35ce"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"b2901ef22c71453b9fd6e13573ee35ce",
          "label":"r11",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":774},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"909233d5c50c422782582d080c88e471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":774},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 操作日志",
                      "target":{
                        "targetType":"page",
                        "url":"操作日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 r12 跟随",
                      "objectsToMoves":[{
                          "objectPath":["ddfaa7b6127c4d4f8eb9b2f5b427b140"],
                          "moveInfo":{
                            "moveType":"withThis",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"ddfaa7b6127c4d4f8eb9b2f5b427b140",
          "label":"r12",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF374D64},
            "location":{
              "x":259,
              "y":824},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4dc72e64a144a5f95754a965cfb483a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF374D64},
                "location":{
                  "x":259,
                  "y":824},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个个人收益账单",
                      "target":{
                        "targetType":"page",
                        "url":"单个个人收益账单.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]},
            "onMove":{
              "description":"OnMove",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]},
{
                      "action":"moveWidget",
                      "description":"移动 部件",
                      "objectsToMoves":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表（总览）/r2_u39.png"}},
{
          "id":"4101fb6f40134e9a9a54b04b93a5c55e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":469,
              "y":90},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d81b4c1080f47b480b90e0069dd4a13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":469,
                  "y":90},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约管理",
                      "target":{
                        "targetType":"page",
                        "url":"签约管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14d6300c3a484d3086379c4c6b868074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":1540,
              "y":91},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c88a89084b74c979a481fecccd64b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":1540,
                  "y":91},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d85b7113010f4bd5b519ae831ddaa6ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":1490,
              "y":91},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b75f600adca4e8d860003080dbd726f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":1490,
                  "y":91},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad8b69246ef64d62a6a1918eb71ae29e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":1440,
              "y":91},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a7d00005df74d1ab99a844b8e7cffc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":1440,
                  "y":91},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f28d7d73406c481c8de38fdab7ac68d4":{
      "scriptId":"u0"},
    "d27ea72b513144c58c175917ba67b4f0":{
      "scriptId":"u1"},
    "676d4df35c6940eb9bf0f2b48c5496a7":{
      "scriptId":"u2"},
    "14f4f97e9cfa49e18b1afd31ac7744df":{
      "scriptId":"u3"},
    "24c377bff6bd4afebed3c085c17bb9fe":{
      "scriptId":"u4"},
    "e31c1782753b45b0820099a7afb28882":{
      "scriptId":"u5"},
    "2e3632fb22f04355ab9e8dc0dabb1c9b":{
      "scriptId":"u6"},
    "b8340cb792ca41fba123060a59aedaaf":{
      "scriptId":"u7"},
    "6e8f9cbbb39546c9ac54df258457d3b1":{
      "scriptId":"u8"},
    "01e18616e8b240dc835bb0d57daaae1c":{
      "scriptId":"u9"},
    "538fe696583b4c138580ee7df0c2d821":{
      "scriptId":"u10"},
    "bf947a2ab0474f398dff2ddc49f74849":{
      "scriptId":"u11"},
    "22a1619bb1174a8880092881f5422b69":{
      "scriptId":"u12"},
    "d036c0f294de4af59f14ec09ae00f363":{
      "scriptId":"u13"},
    "1c0c775e39944a38879a8f345b889ca4":{
      "scriptId":"u14"},
    "8a9624f2a0604a588b219708f59eac61":{
      "scriptId":"u15"},
    "36980cb5e7e74963912b1b83faca8bd6":{
      "scriptId":"u16"},
    "bfff0898f03e4c2fae6113aba4da7b2a":{
      "scriptId":"u17"},
    "5436d03ff2bc45399675e9ab6ced4a2b":{
      "scriptId":"u18"},
    "98f8697dd5564fc69dba59e23c506150":{
      "scriptId":"u19"},
    "2b7c54e7aecc4770b0105c4575bbb459":{
      "scriptId":"u20"},
    "3f2fa7825ad2468eb31168ab732cf823":{
      "scriptId":"u21"},
    "2c2f0144467a4bb5889c4a64c88ffbf5":{
      "scriptId":"u22"},
    "fde509fcc7bf4a808bf030a40ad246a9":{
      "scriptId":"u23"},
    "a6a060b0c35a4901807cbf577a23fa07":{
      "scriptId":"u24"},
    "ce7023f4433f4886a8b5d5dd0d8d0978":{
      "scriptId":"u25"},
    "4e68c86e8bc7497e804565604e2518f0":{
      "scriptId":"u26"},
    "5215ce0bd3df4d8695d5369e4e743052":{
      "scriptId":"u27"},
    "ac5c61b031ea4443a28262143f548295":{
      "scriptId":"u28"},
    "ddf1811f10b84a378f692c317f184c39":{
      "scriptId":"u29"},
    "ca04379e7826405d8d0be38bda4c2844":{
      "scriptId":"u30"},
    "ac46afad82a84ed2913fcbc2f96debb1":{
      "scriptId":"u31"},
    "5e3ced70a0c94dd69076c6eb395c0529":{
      "scriptId":"u32"},
    "20251e4ea59743e7ba164a4a44b3bcbe":{
      "scriptId":"u33"},
    "7f50422941d64f3da28e4099b9fae32b":{
      "scriptId":"u34"},
    "0c6c844b2c7042b9944b7fcb8696b56d":{
      "scriptId":"u35"},
    "a3d7086365104e12901cfbe3401208ea":{
      "scriptId":"u36"},
    "c9613b45abfc4edfb3573568213de8ab":{
      "scriptId":"u37"},
    "19cfca2a551f44b99fdedba0e11e1e29":{
      "scriptId":"u38"},
    "540b9ed9c9ff4bd099547c07d6a5e5af":{
      "scriptId":"u39"},
    "f83a09ffecc540f6afec4f7a1f36f60a":{
      "scriptId":"u40"},
    "12178199e32d47d086ca90013fadd50a":{
      "scriptId":"u41"},
    "ed62e39c52a644dc872eccf7b32b3b22":{
      "scriptId":"u42"},
    "a8ac5de440ac434aa6adabe96f3d220c":{
      "scriptId":"u43"},
    "214683a784a94d3c9ca3d8bd5c03f674":{
      "scriptId":"u44"},
    "827aa1b15d1c4151b69fa55c163d1e7e":{
      "scriptId":"u45"},
    "cda2abf721dc45dfb98847887e98e520":{
      "scriptId":"u46"},
    "b214cb2a1ef04fb3999244cf6fde0c49":{
      "scriptId":"u47"},
    "ffa96b3ee67845b783e5a9acfb59fa26":{
      "scriptId":"u48"},
    "b2901ef22c71453b9fd6e13573ee35ce":{
      "scriptId":"u49"},
    "909233d5c50c422782582d080c88e471":{
      "scriptId":"u50"},
    "ddfaa7b6127c4d4f8eb9b2f5b427b140":{
      "scriptId":"u51"},
    "c4dc72e64a144a5f95754a965cfb483a":{
      "scriptId":"u52"},
    "4101fb6f40134e9a9a54b04b93a5c55e":{
      "scriptId":"u53"},
    "3d81b4c1080f47b480b90e0069dd4a13":{
      "scriptId":"u54"},
    "14d6300c3a484d3086379c4c6b868074":{
      "scriptId":"u55"},
    "3c88a89084b74c979a481fecccd64b78":{
      "scriptId":"u56"},
    "d85b7113010f4bd5b519ae831ddaa6ec":{
      "scriptId":"u57"},
    "8b75f600adca4e8d860003080dbd726f":{
      "scriptId":"u58"},
    "ad8b69246ef64d62a6a1918eb71ae29e":{
      "scriptId":"u59"},
    "8a7d00005df74d1ab99a844b8e7cffc2":{
      "scriptId":"u60"}}});