$axure.loadCurrentPage({
  "url":"临退签约.html",
  "generationDate":new Date(1516182764752.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"4194fbfb1e894ccc907e8640ffeb4e72",
    "type":"Axure:Page",
    "name":"临退签约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f97e3659730a4fb9b0ec10ced222d960",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":1080,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bc5fa8f5ab047cf9a2edd0c6789c9fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":1080,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增签约/u0.png"}},
{
          "id":"3d5c2e4c7ea34b76bf04feaa7f955008",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":130,
              "y":130},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd87ddcee40549ff826b5260fe1fdabf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":130,
                  "y":130},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"811993b2ef9d4be4b985dc32722e190c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":194},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93be24f62d524692ae894c79ed6c8bec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":194},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eadd9e0d652443079a68a71c0534e558",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":224},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c538ae8d09564ebeb5fdbea716576035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":224},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"960aa6e94fd94d5a877a886f7a3c8afc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":254},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdc3b84b6321427b8a0f7d821eb7cd51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":254},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3041d1809bf246d8a841cd71bf55e4c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":284},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84097e47c0ac4062bfaef3404d6dea10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":284},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c6ee74faa84432eb8ed951f209f9af4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":314},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af37c85b576649b88d6edfa7888bfea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":314},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e3ebf1058eb49fc9b0ecf9e24ac2ef9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":344},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ccb8913b48e4d2b9dd656abd09055bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":344},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fd78248317145c9855fafd2531770f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":374},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae5da2962d8049618699c612f23fe7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":374},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c2e5fed4bfd43ecbe8b8f1efa627195",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":404},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d45fbe3bd24fcc97a19ff6d0227a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":404},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55e5756d76b94d5892d7988783323f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":434},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6abed4004a7c437082c5f1c52f8561f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":434},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17a921658c6f462ebad3de9114d66ba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":464},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2ec17576c0f4c7fb5baa57c3316def5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":464},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"618973c80c3f4e4c810523eae7c13be2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":230,
              "y":494},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bb4d05b48134936b2b14e3ea3ddd6e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":230,
                  "y":494},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29df13511e83421696d731816afc64ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":524},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f26fab8b3149d0a4f485dbe7e30994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":524},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8233a8c078c841a9b50afcd49fc93156",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":554},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3976f24824e1410981dfbb7c2fb16f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":554},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da76aed5acff47d2af4c5b8b1e1161fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":314},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2023fd7c5cd940f9ba8f99b57daefec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":314},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"270fb62e428149108dce626eb64de821",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":545,
              "y":660},
            "size":{
              "width":190,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提交申请确认弹窗",
                      "objectsToFades":[{
                          "objectPath":["14f1c8d934204d659bdd49d586027b90"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"efa9f261b88749a0abe7321b90cd62dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":398,
              "y":560},
            "size":{
              "width":182,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b60ab12703c41e0b6a0e0d7f5859069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":398,
                  "y":560},
                "size":{
                  "width":182,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"044a55f0007a4505a6dea34f794c03ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":194},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946bc4bb6d744a62b406d2856654259d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":194},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebe8bc3a66b04ddf88d55b877fb879fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":494},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bbaaf84dce4de0a46e5e20f6d64cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":494},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55be195661ad40a1b1a5a69d12a95b35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":254},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f456dd309d440a08d163f0baddfb567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":254},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e45eb9253b764050b6049055e666a233",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":284},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db7b541a5db24f9e8b00f5bf279c3773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":284},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35c7fb8df530446c9aca57f758fbf5b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":224},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05c83550ec8a4b3bb96df629c6d3adba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":224},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cf58bc686864518b44dde3352746433",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":343},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b51cf6be5e394101952bb607dcc83372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":343},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17d7baff962946f281beaf45ec82f165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":372},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c4088fe8694a0e9ad70f9563882e62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":372},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"388fe06ad3a545d89bc63f98f008e4b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":404},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa056aada0446fdbb310c119e741b47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":404},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"969c436bd1bb4d1c81ec749e1bfda561",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":390,
              "y":434},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7ad724293a54749841bc079292e0d71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":434},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cd8b493503d4f68828911be1706b480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":390,
              "y":464},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb35d23ab47d4a84962b25aca59d9da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":464},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0304b444f484e81becb44f715b745cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":524},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d65d9ee8a83f4d8bb4f72891d4769b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":390,
                  "y":524},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8a9653f3bed477db7a864f994d31a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":710,
              "y":224},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12c2de1c16784beb9014fb6b4d9fc4c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":710,
                  "y":224},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f879d7313a4f4cf2946a3fa338ad5a6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":710,
              "y":254},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc91b694026e4258b9689d03cbe3caae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":710,
                  "y":254},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf0c6c44f51d41729eba2add3e503459",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":710,
              "y":284},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0d75b3458dd4be2b86c8c2404a2ab85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":710,
                  "y":284},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1f4ef13bc2946d4929bf22c8adfca03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":870,
              "y":284},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b6f941d858b42b994f64b777df35a55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":870,
                  "y":284},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b7f4756bf604b8cac8db347d30c3202",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":870,
              "y":224},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"373ba4ae39254999a57216dce8e5d1ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":870,
                  "y":224},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd5434bb01814351b8aba5ab1ed07831",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":710,
              "y":194},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fcab712970143afb86080f1338d9f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":710,
                  "y":194},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bb82581049342ce88728fc7e3f5fc17",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":870,
              "y":190.5},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"14f1c8d934204d659bdd49d586027b90",
          "label":"提交申请确认弹窗",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":440,
              "y":270},
            "size":{
              "width":400,
              "height":300},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"23ef2d58ab714dd0a6eb87eccf96ffec",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aa282a3bac464e95acec6187eceedc28",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":400,
                      "height":300}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b3565c31aec4753acbfef4bae79dc5c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":400,
                          "height":300}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/收益管理/u543.png"}},
{
                  "id":"8a6a4774f790413e931d91c5e0ec6b5f",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":152,
                      "y":14},
                    "size":{
                      "width":97,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74c74b67cb8147a6a0fbfe2eb0ba0620",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":152,
                          "y":14},
                        "size":{
                          "width":97,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"89975ba4093e4ec5a75677159317bc26",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e8d0153755d4ba8b0c33b8914105377",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3579ce30135f4a729c71729a72962ccb",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":200,
                      "y":50},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7963a3f08e0d4b0dbcc301f8c71af565",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":200,
                          "y":50},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0baa4e71540148bbb3b19e652fefc53d",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":100,
                      "y":73},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"102f68425a1a47ca8ed853d1bed6cde7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":100,
                          "y":73},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c9e6960a170456fbf9b28a06a0ba955",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":200,
                      "y":73},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"53cec89856604d898fc135250577227b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":200,
                          "y":73},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8feaf544d5804094a4414ece6a3fddba",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":100,
                      "y":96},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"259a5d279da64a63954ae73eee59b4a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":100,
                          "y":96},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2424129d618a41d3b4058ff5f5f58c54",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":200,
                      "y":96},
                    "size":{
                      "width":54,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f0bdc2b0b3bd457784bf720e9cb2b041",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":200,
                          "y":96},
                        "size":{
                          "width":54,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1108e6b4390404897f8fa13ecdf3427",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":100,
                      "y":119},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dfa2d00c70f44d83a4184de62c1df731",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":100,
                          "y":119},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"813b2d3adcab419d8ea19e14b12b0f5f",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":200,
                      "y":119},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a2a0ed08f5d454fba90ffd5cd349e79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":200,
                          "y":119},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f967892155f4c50b1db129cb3fb4361",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":100,
                      "y":142},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe91525b84b8463a8985dd8cd2c7d77b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":100,
                          "y":142},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3b2922a832df4e8c8371a145062ef5d7",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":200,
                      "y":142},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0507abb6c61e4c279a039ea0f3b7fa58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":200,
                          "y":142},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6c4044464c4d45f4bf0523cc404dccb1",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontWeight":"200",
                    "location":{
                      "x":100,
                      "y":165},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04ee513503104990a58b989f0df0df9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontWeight":"200",
                        "location":{
                          "x":100,
                          "y":165},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9f3dbb233d3e4e62bc50eea911d078c1",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":200,
                      "y":165},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21ebbdc623c44f4f8c60553d2a373d0c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":200,
                          "y":165},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"858088aebcac4c4087283b44619df609",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":194,
                      "y":192},
                    "size":{
                      "width":13,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cfc32a69803c4a6ea1f15804bfa2c214",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":194,
                          "y":192},
                        "size":{
                          "width":13,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2deaa1c825574f2090b05ef9cd7c6be8",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontWeight":"200",
                    "location":{
                      "x":45,
                      "y":240},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a1bbe8ad7f6440e9a50cfbb5767e38b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontWeight":"200",
                        "location":{
                          "x":45,
                          "y":240},
                        "size":{
                          "width":150,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 提交申请确认弹窗",
                              "objectsToFades":[{
                                  "objectPath":["14f1c8d934204d659bdd49d586027b90"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/客户编辑/u92.png"}},
{
                  "id":"de51e2889dc547b08457b6b22fab3793",
                  "label":"",
                  "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontWeight":"200",
                    "location":{
                      "x":205,
                      "y":240},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc6751448e324b6e84e618163c0dfc93",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"14f1c8d934204d659bdd49d586027b90",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontWeight":"200",
                        "location":{
                          "x":205,
                          "y":240},
                        "size":{
                          "width":150,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 签约详情（审批中）",
                              "target":{
                                "targetType":"page",
                                "url":"签约详情（审批中）.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/客户编辑/u92.png"}}]}]},
{
          "id":"003ea2ee1227475fbfa2531e0677cc51",
          "label":"临退手续费",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":254},
            "size":{
              "width":80,
              "height":15}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c331e6397e2c446cb8d19b853734e861",
              "label":"显示",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8698741d88fc4ac282ec1e627a8d20a0",
                  "label":"",
                  "parentDynamicPanel":"003ea2ee1227475fbfa2531e0677cc51",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":40,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9cdb446aa474187bf39b40e8639016a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"003ea2ee1227475fbfa2531e0677cc51",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":40,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"17dddbcb8c604884bdd9e0648f7c0321",
              "label":"修改",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a0993a873e0a4e8390b37702a44ea5fe",
                  "label":"",
                  "parentDynamicPanel":"003ea2ee1227475fbfa2531e0677cc51",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontWeight":"200",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onTextChange":{
                      "description":"OnTextChange",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 修改按钮 到 完成",
                              "panelsToStates":[{
                                  "panelPath":["fc782498388d4fa9a4953b7654ccee8f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}}}]}]},
{
          "id":"fc782498388d4fa9a4953b7654ccee8f",
          "label":"修改按钮",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":254},
            "size":{
              "width":40,
              "height":15}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"cbc2fd39de5d4958a8c3d2a25db75573",
              "label":"修改",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c77d9ee2fca84eb9ae0b094111c4fd08",
                  "label":"",
                  "parentDynamicPanel":"fc782498388d4fa9a4953b7654ccee8f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF199ED7,
                      "opacity":1},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39a026e4838848dc94baaf48e956b7bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc782498388d4fa9a4953b7654ccee8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF199ED7,
                          "opacity":1},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 临退手续费 到 修改",
                              "panelsToStates":[{
                                  "panelPath":["003ea2ee1227475fbfa2531e0677cc51"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"59372f222bc34454a3d4873bffcfccf2",
              "label":"完成",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e084c52416b6437fba0225aceb18954a",
                  "label":"",
                  "parentDynamicPanel":"fc782498388d4fa9a4953b7654ccee8f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF199ED7,
                      "opacity":1},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"909aa9272dbe4d9f9c24f4fc13f2e895",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc782498388d4fa9a4953b7654ccee8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF199ED7,
                          "opacity":1},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 临退手续费 到 显示",
                              "panelsToStates":[{
                                  "panelPath":["003ea2ee1227475fbfa2531e0677cc51"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "f97e3659730a4fb9b0ec10ced222d960":{
      "scriptId":"u0"},
    "7bc5fa8f5ab047cf9a2edd0c6789c9fd":{
      "scriptId":"u1"},
    "3d5c2e4c7ea34b76bf04feaa7f955008":{
      "scriptId":"u2"},
    "bd87ddcee40549ff826b5260fe1fdabf":{
      "scriptId":"u3"},
    "811993b2ef9d4be4b985dc32722e190c":{
      "scriptId":"u4"},
    "93be24f62d524692ae894c79ed6c8bec":{
      "scriptId":"u5"},
    "eadd9e0d652443079a68a71c0534e558":{
      "scriptId":"u6"},
    "c538ae8d09564ebeb5fdbea716576035":{
      "scriptId":"u7"},
    "960aa6e94fd94d5a877a886f7a3c8afc":{
      "scriptId":"u8"},
    "fdc3b84b6321427b8a0f7d821eb7cd51":{
      "scriptId":"u9"},
    "3041d1809bf246d8a841cd71bf55e4c8":{
      "scriptId":"u10"},
    "84097e47c0ac4062bfaef3404d6dea10":{
      "scriptId":"u11"},
    "4c6ee74faa84432eb8ed951f209f9af4":{
      "scriptId":"u12"},
    "af37c85b576649b88d6edfa7888bfea4":{
      "scriptId":"u13"},
    "1e3ebf1058eb49fc9b0ecf9e24ac2ef9":{
      "scriptId":"u14"},
    "8ccb8913b48e4d2b9dd656abd09055bf":{
      "scriptId":"u15"},
    "0fd78248317145c9855fafd2531770f5":{
      "scriptId":"u16"},
    "ae5da2962d8049618699c612f23fe7bd":{
      "scriptId":"u17"},
    "5c2e5fed4bfd43ecbe8b8f1efa627195":{
      "scriptId":"u18"},
    "e8d45fbe3bd24fcc97a19ff6d0227a00":{
      "scriptId":"u19"},
    "55e5756d76b94d5892d7988783323f0f":{
      "scriptId":"u20"},
    "6abed4004a7c437082c5f1c52f8561f5":{
      "scriptId":"u21"},
    "17a921658c6f462ebad3de9114d66ba0":{
      "scriptId":"u22"},
    "a2ec17576c0f4c7fb5baa57c3316def5":{
      "scriptId":"u23"},
    "618973c80c3f4e4c810523eae7c13be2":{
      "scriptId":"u24"},
    "3bb4d05b48134936b2b14e3ea3ddd6e8":{
      "scriptId":"u25"},
    "29df13511e83421696d731816afc64ad":{
      "scriptId":"u26"},
    "44f26fab8b3149d0a4f485dbe7e30994":{
      "scriptId":"u27"},
    "8233a8c078c841a9b50afcd49fc93156":{
      "scriptId":"u28"},
    "3976f24824e1410981dfbb7c2fb16f31":{
      "scriptId":"u29"},
    "da76aed5acff47d2af4c5b8b1e1161fe":{
      "scriptId":"u30"},
    "2023fd7c5cd940f9ba8f99b57daefec3":{
      "scriptId":"u31"},
    "270fb62e428149108dce626eb64de821":{
      "scriptId":"u32"},
    "efa9f261b88749a0abe7321b90cd62dc":{
      "scriptId":"u33"},
    "4b60ab12703c41e0b6a0e0d7f5859069":{
      "scriptId":"u34"},
    "044a55f0007a4505a6dea34f794c03ef":{
      "scriptId":"u35"},
    "946bc4bb6d744a62b406d2856654259d":{
      "scriptId":"u36"},
    "ebe8bc3a66b04ddf88d55b877fb879fd":{
      "scriptId":"u37"},
    "78bbaaf84dce4de0a46e5e20f6d64cd4":{
      "scriptId":"u38"},
    "55be195661ad40a1b1a5a69d12a95b35":{
      "scriptId":"u39"},
    "5f456dd309d440a08d163f0baddfb567":{
      "scriptId":"u40"},
    "e45eb9253b764050b6049055e666a233":{
      "scriptId":"u41"},
    "db7b541a5db24f9e8b00f5bf279c3773":{
      "scriptId":"u42"},
    "35c7fb8df530446c9aca57f758fbf5b8":{
      "scriptId":"u43"},
    "05c83550ec8a4b3bb96df629c6d3adba":{
      "scriptId":"u44"},
    "1cf58bc686864518b44dde3352746433":{
      "scriptId":"u45"},
    "b51cf6be5e394101952bb607dcc83372":{
      "scriptId":"u46"},
    "17d7baff962946f281beaf45ec82f165":{
      "scriptId":"u47"},
    "54c4088fe8694a0e9ad70f9563882e62":{
      "scriptId":"u48"},
    "388fe06ad3a545d89bc63f98f008e4b4":{
      "scriptId":"u49"},
    "2aa056aada0446fdbb310c119e741b47":{
      "scriptId":"u50"},
    "969c436bd1bb4d1c81ec749e1bfda561":{
      "scriptId":"u51"},
    "b7ad724293a54749841bc079292e0d71":{
      "scriptId":"u52"},
    "9cd8b493503d4f68828911be1706b480":{
      "scriptId":"u53"},
    "fb35d23ab47d4a84962b25aca59d9da5":{
      "scriptId":"u54"},
    "a0304b444f484e81becb44f715b745cb":{
      "scriptId":"u55"},
    "d65d9ee8a83f4d8bb4f72891d4769b4a":{
      "scriptId":"u56"},
    "b8a9653f3bed477db7a864f994d31a31":{
      "scriptId":"u57"},
    "12c2de1c16784beb9014fb6b4d9fc4c6":{
      "scriptId":"u58"},
    "f879d7313a4f4cf2946a3fa338ad5a6d":{
      "scriptId":"u59"},
    "fc91b694026e4258b9689d03cbe3caae":{
      "scriptId":"u60"},
    "cf0c6c44f51d41729eba2add3e503459":{
      "scriptId":"u61"},
    "e0d75b3458dd4be2b86c8c2404a2ab85":{
      "scriptId":"u62"},
    "c1f4ef13bc2946d4929bf22c8adfca03":{
      "scriptId":"u63"},
    "2b6f941d858b42b994f64b777df35a55":{
      "scriptId":"u64"},
    "0b7f4756bf604b8cac8db347d30c3202":{
      "scriptId":"u65"},
    "373ba4ae39254999a57216dce8e5d1ae":{
      "scriptId":"u66"},
    "fd5434bb01814351b8aba5ab1ed07831":{
      "scriptId":"u67"},
    "2fcab712970143afb86080f1338d9f21":{
      "scriptId":"u68"},
    "2bb82581049342ce88728fc7e3f5fc17":{
      "scriptId":"u69"},
    "14f1c8d934204d659bdd49d586027b90":{
      "scriptId":"u70"},
    "aa282a3bac464e95acec6187eceedc28":{
      "scriptId":"u71"},
    "9b3565c31aec4753acbfef4bae79dc5c":{
      "scriptId":"u72"},
    "8a6a4774f790413e931d91c5e0ec6b5f":{
      "scriptId":"u73"},
    "74c74b67cb8147a6a0fbfe2eb0ba0620":{
      "scriptId":"u74"},
    "89975ba4093e4ec5a75677159317bc26":{
      "scriptId":"u75"},
    "5e8d0153755d4ba8b0c33b8914105377":{
      "scriptId":"u76"},
    "3579ce30135f4a729c71729a72962ccb":{
      "scriptId":"u77"},
    "7963a3f08e0d4b0dbcc301f8c71af565":{
      "scriptId":"u78"},
    "0baa4e71540148bbb3b19e652fefc53d":{
      "scriptId":"u79"},
    "102f68425a1a47ca8ed853d1bed6cde7":{
      "scriptId":"u80"},
    "8c9e6960a170456fbf9b28a06a0ba955":{
      "scriptId":"u81"},
    "53cec89856604d898fc135250577227b":{
      "scriptId":"u82"},
    "8feaf544d5804094a4414ece6a3fddba":{
      "scriptId":"u83"},
    "259a5d279da64a63954ae73eee59b4a4":{
      "scriptId":"u84"},
    "2424129d618a41d3b4058ff5f5f58c54":{
      "scriptId":"u85"},
    "f0bdc2b0b3bd457784bf720e9cb2b041":{
      "scriptId":"u86"},
    "f1108e6b4390404897f8fa13ecdf3427":{
      "scriptId":"u87"},
    "dfa2d00c70f44d83a4184de62c1df731":{
      "scriptId":"u88"},
    "813b2d3adcab419d8ea19e14b12b0f5f":{
      "scriptId":"u89"},
    "0a2a0ed08f5d454fba90ffd5cd349e79":{
      "scriptId":"u90"},
    "3f967892155f4c50b1db129cb3fb4361":{
      "scriptId":"u91"},
    "fe91525b84b8463a8985dd8cd2c7d77b":{
      "scriptId":"u92"},
    "3b2922a832df4e8c8371a145062ef5d7":{
      "scriptId":"u93"},
    "0507abb6c61e4c279a039ea0f3b7fa58":{
      "scriptId":"u94"},
    "6c4044464c4d45f4bf0523cc404dccb1":{
      "scriptId":"u95"},
    "04ee513503104990a58b989f0df0df9a":{
      "scriptId":"u96"},
    "9f3dbb233d3e4e62bc50eea911d078c1":{
      "scriptId":"u97"},
    "21ebbdc623c44f4f8c60553d2a373d0c":{
      "scriptId":"u98"},
    "858088aebcac4c4087283b44619df609":{
      "scriptId":"u99"},
    "cfc32a69803c4a6ea1f15804bfa2c214":{
      "scriptId":"u100"},
    "2deaa1c825574f2090b05ef9cd7c6be8":{
      "scriptId":"u101"},
    "a1bbe8ad7f6440e9a50cfbb5767e38b0":{
      "scriptId":"u102"},
    "de51e2889dc547b08457b6b22fab3793":{
      "scriptId":"u103"},
    "bc6751448e324b6e84e618163c0dfc93":{
      "scriptId":"u104"},
    "003ea2ee1227475fbfa2531e0677cc51":{
      "scriptId":"u105"},
    "8698741d88fc4ac282ec1e627a8d20a0":{
      "scriptId":"u106"},
    "b9cdb446aa474187bf39b40e8639016a":{
      "scriptId":"u107"},
    "a0993a873e0a4e8390b37702a44ea5fe":{
      "scriptId":"u108"},
    "fc782498388d4fa9a4953b7654ccee8f":{
      "scriptId":"u109"},
    "c77d9ee2fca84eb9ae0b094111c4fd08":{
      "scriptId":"u110"},
    "39a026e4838848dc94baaf48e956b7bd":{
      "scriptId":"u111"},
    "e084c52416b6437fba0225aceb18954a":{
      "scriptId":"u112"},
    "909aa9272dbe4d9f9c24f4fc13f2e895":{
      "scriptId":"u113"}}});