$axure.loadCurrentPage({
  "url":"签约详情（审批中）.html",
  "generationDate":new Date(1516182762487.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"fd891b665651400fb931755b2552cb62",
    "type":"Axure:Page",
    "name":"签约详情（审批中）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e53252f732f6460ca4708750749b7477",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":1080,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c0f2eee2db14be6a8377587c4ab79a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":1080,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约详情（审批中）/u0.png"}},
{
          "id":"14415ae981144ef09bf2fcff6af6b2d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":170},
            "size":{
              "width":1060,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd4e69d280ab480b910cea6a5c7f5d09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":170},
                "size":{
                  "width":1060,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u0.png"}},
{
          "id":"c2484a75e2ba4acbb0162ad2501172c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":443,
              "y":240},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9a7f46dadd4a00a89c05920425b713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":443,
                  "y":240},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u2.png"}},
{
          "id":"c6a4763250ed465fbd0a74dccf164ddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":483,
              "y":255},
            "size":{
              "width":40,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e45a1907d7b146f0ad29ae7173e8e60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":483,
                  "y":255},
                "size":{
                  "width":40,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u24.png"}},
{
          "id":"0f2643e313be418fa4c57749b36f0451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":561,
              "y":240},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e658ee958e304f3283b8a102985546ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":561,
                  "y":240},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u6.png"}},
{
          "id":"2ebc6acae22c49baad1ba46984d7e7d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":601,
              "y":255},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76da3262ff6a4158aad7e00dafc0d208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":601,
                  "y":255},
                "size":{
                  "width":80,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约详情（审批中）/u10.png"}},
{
          "id":"29bec252d4bb4442967b7bf52f957deb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":679,
              "y":240},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e6646f75264e11b4a32fe6446150fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":679,
                  "y":240},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u6.png"}},
{
          "id":"394960037b954ec8a63502d4885fb91b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":719,
              "y":255},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1220d29a254944deb78bd27c72885ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":719,
                  "y":255},
                "size":{
                  "width":80,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约详情（审批中）/u10.png"}},
{
          "id":"00a9c7d1ccef4d16803f6c4ea57df5f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":797,
              "y":240},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bed3bdd5f04480f9ee50a8aad69e8f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":797,
                  "y":240},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u6.png"}},
{
          "id":"75c442c30d014a0e822e070606fc8b6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":523,
              "y":255},
            "size":{
              "width":40,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f41558177da485f97212c0da6c04231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":523,
                  "y":255},
                "size":{
                  "width":40,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结算审批详情）/u16.png"}},
{
          "id":"eda4b2d7231a42f9a0fad9271c683b3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":190},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa564dc2748c4b698e20315f9d95a29b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":190},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b50a76f4f2446f2a85ab887cc63ad31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":410,
              "y":290},
            "size":{
              "width":105,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4d9b66fedd3446ebfd1112273dfccd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":290},
                "size":{
                  "width":105,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e41ff2cd8404a0483c71ed71c945c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":542,
              "y":290},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58aea97d99194dbda0ac2e317ccb17b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":542,
                  "y":290},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"249c8974febd48cbaf13a0c12dc69b76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":672,
              "y":290},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8a5591e4314779bc6768e4285fbe26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":672,
                  "y":290},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26d269e2285d4541a8342c7a959ef548",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":778,
              "y":290},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9db9d2fcb6ad4e288e1b6409531663e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":778,
                  "y":290},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cffc14833b49443ba5e5d7c8a1459e0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":380},
            "size":{
              "width":1060,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"003e722c97e14f0892db8b62de853873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":380},
                "size":{
                  "width":1060,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约详情（审批中）/u30.png"}},
{
          "id":"b0d327a8683e401d8f1c6fe597dec351",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":440},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36a8f4e5e9b34e4194e2022dee9a9295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":440},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41966c6a8a5b45e6a036187f9993c6d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":470},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd147b50d22e4446adff7ad7f49a7dff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":470},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96deed4071e64c76a88ba1f540b9934f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":500},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9956ca9cbaab4c6e86134b3255a28bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":500},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"632f344d438d440994a816631259bd7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":530},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dea0359c08f4d93891bcb838105a400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":530},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b834284fcebc4ceaa2bc4f2a1a986a0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":560},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f8b49435c8c4e09b2dfefd323e922e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":560},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6aa01b50518452cbc0cc5793fc9b0b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":590},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb8454fb85744c2eb6f6ffb99b6883a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":590},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ee594bf1ee74c6aa531d2ffb52d4569",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":253,
              "y":620},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1c060a95f58429aaf52c15788bcf071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":253,
                  "y":620},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8bee2adbb07442fb7b79b8f3578a6ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":697,
              "y":440},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034a35b0595b4e6aaedf93af18b981ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":697,
                  "y":440},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"524e8835daa743dc9155596525581771",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":697,
              "y":470},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6957bd8c51dd4e6da5c3b1293413610d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":697,
                  "y":470},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa9d9941f6954383a4601453c4070af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":697,
              "y":500},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480fc1049b3a46948ab964c7cd00807e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":697,
                  "y":500},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fe717a892564c3294e7b148e462079e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":697,
              "y":530},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62831ebf128a4df581cf1254a459be6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":697,
                  "y":530},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b851b07ee1f047c8b8b5a345fce7a676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":697,
              "y":560},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d79701254e5d467c9d2af32ddf8d6c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":697,
                  "y":560},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4620184f77440c59b530557260d6cef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":697,
              "y":590},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b6df28f1d054304bd256d9b97821f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":697,
                  "y":590},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94f1622e91664cf486626ecdac8902dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":560},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65d152ad0dfe4fbda3bcad8063bbc005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":560},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fea425ecc8be4835af8b390bd157cd99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":589},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ccc3923dd6043c5857f5af99858a470",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":589},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8af3e3fe5b747fea753c6eb631b5c8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":619},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf43d632c3db426e85854a96d6a55010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":619},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f86ce68a22d54a7c8e489d462c2159e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":469},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f6ed5c9ddc4ee08e185ee050c4ca76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":469},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c32a4a1ac86e44f0a857689f96bb7584",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":499},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e70511e87a4c9c95907248b5bbf6c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":499},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14d10306eaa34db5b1b96bdfc600c55f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":530},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfbd7c4472ab49b8890160eaa2f72213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":530},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"435dc1e45cbb43e197e54d080ffdb24d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":413,
              "y":440},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f0d8f002226413ca9bed848202085be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":413,
                  "y":440},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1656597f97a44a66849a4f8bc7af7f97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":857,
              "y":499},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a6b198dcaff4b3cae6dce22b5bfa39c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":857,
                  "y":499},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"865fb93dbd2a466792846668f6c6d45d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":857,
              "y":530},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6833d31b1394922b32cca3991ea64ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":857,
                  "y":530},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"416b57fe866f4a4e873e67f8aed7eb7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":857,
              "y":560},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517d6fcd72584f76bca3eb5e89468a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":857,
                  "y":560},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"245c91f5f492452e990d8bc0e23f840e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":857,
              "y":440},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a61b11acda34459b742f8a60639b5dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":857,
                  "y":440},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a370d8eb554a4718ab958794e6dd7bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":857,
              "y":470},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54480a7563d74b178795868cbf382914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":857,
                  "y":470},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ee5284f11204eadabba87f2f98c7c3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":857,
              "y":590},
            "size":{
              "width":170,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a89ada7f093847fd84d7f7f89c5a9fb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":857,
                  "y":590},
                "size":{
                  "width":170,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb5aa400d5a3435ab2fe8deb2bf2b1bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":400},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa878a3955824ec7a65777c25375d2a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":400},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f12f4f4cb8ba40edb9d92ef88aead172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":1060,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8347a01d0c47689fb91cb1ee0b31a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":1060,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约详情（审批中）/u86.png"}},
{
          "id":"8a212cafdbba4a2b83ce9d07e9295d11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":127},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b310c80d422d435f9276c5d917f86b95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":127},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89c8d080b88e408baa4c4edb9e8cd71d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "location":{
              "x":961,
              "y":128},
            "size":{
              "width":189,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff755626978a484cb0b71cb250b9ce4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "location":{
                  "x":961,
                  "y":128},
                "size":{
                  "width":189,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc426294bb434a2fbaff2156066c8fd6",
          "label":"历史审批纪录",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":680},
            "size":{
              "width":1060,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e14c116083004100971bcb7bdea89db2",
              "label":"收回",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"04f57f056be942b1a4415c86dbb8140c",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":1060,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a81b72ff8d4f4fde8f2a593c330e9d83",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":1060,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/结算审批详情）/u29.png"}},
{
                  "id":"283a24884bcb4f468a94a4cd74436d8a",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":97,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d00f7a9c505a41278cb27799e64c29d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":97,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b907892bef064a7c9ff71f41a8bb6428",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":1020,
                      "y":20},
                    "size":{
                      "width":20,
                      "height":12},
                    "rotation":"180",
                    "textRotation":"180"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6ddebd0224a45559a8526afe86ff787",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":1020,
                          "y":20},
                        "size":{
                          "width":20,
                          "height":12},
                        "rotation":"180",
                        "textRotation":"180"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 历史审批纪录 到 展开",
                              "panelsToStates":[{
                                  "panelPath":["bc426294bb434a2fbaff2156066c8fd6"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/结算审批详情）/u33.png"}}]},
{
              "id":"4ad4c633d48d45e09a0ec92685b3c53e",
              "label":"展开",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"53e2654cb86f4981ab86d24d869418a3",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":1060,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2810b387cdc94ec5ae736dc89fb26bfb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":1060,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/结算审批详情）/u35.png"}},
{
                  "id":"3fe380f7951b4dbfb20cb8df502d8dc5",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":97,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f936c507f2374b398fd82dd414dd5eab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":97,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"27456f636feb42b98fc7392b7ae0b289",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":466,
                      "y":72},
                    "size":{
                      "width":129,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29cb45852af4442b8054a494b54c07e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":466,
                          "y":72},
                        "size":{
                          "width":129,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"02ac6106ab984385a2f287f3d2ac0520",
                  "label":"",
                  "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":1020,
                      "y":20},
                    "size":{
                      "width":20,
                      "height":12}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d4a62751e8284c22b2b5b7e703c9eab1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc426294bb434a2fbaff2156066c8fd6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":1020,
                          "y":20},
                        "size":{
                          "width":20,
                          "height":12}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 历史审批纪录 到 收回",
                              "panelsToStates":[{
                                  "panelPath":["bc426294bb434a2fbaff2156066c8fd6"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/结算审批详情）/u33.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "e53252f732f6460ca4708750749b7477":{
      "scriptId":"u0"},
    "6c0f2eee2db14be6a8377587c4ab79a0":{
      "scriptId":"u1"},
    "14415ae981144ef09bf2fcff6af6b2d9":{
      "scriptId":"u2"},
    "bd4e69d280ab480b910cea6a5c7f5d09":{
      "scriptId":"u3"},
    "c2484a75e2ba4acbb0162ad2501172c6":{
      "scriptId":"u4"},
    "0a9a7f46dadd4a00a89c05920425b713":{
      "scriptId":"u5"},
    "c6a4763250ed465fbd0a74dccf164ddb":{
      "scriptId":"u6"},
    "e45a1907d7b146f0ad29ae7173e8e60e":{
      "scriptId":"u7"},
    "0f2643e313be418fa4c57749b36f0451":{
      "scriptId":"u8"},
    "e658ee958e304f3283b8a102985546ea":{
      "scriptId":"u9"},
    "2ebc6acae22c49baad1ba46984d7e7d6":{
      "scriptId":"u10"},
    "76da3262ff6a4158aad7e00dafc0d208":{
      "scriptId":"u11"},
    "29bec252d4bb4442967b7bf52f957deb":{
      "scriptId":"u12"},
    "b2e6646f75264e11b4a32fe6446150fd":{
      "scriptId":"u13"},
    "394960037b954ec8a63502d4885fb91b":{
      "scriptId":"u14"},
    "1220d29a254944deb78bd27c72885ccc":{
      "scriptId":"u15"},
    "00a9c7d1ccef4d16803f6c4ea57df5f6":{
      "scriptId":"u16"},
    "7bed3bdd5f04480f9ee50a8aad69e8f9":{
      "scriptId":"u17"},
    "75c442c30d014a0e822e070606fc8b6b":{
      "scriptId":"u18"},
    "8f41558177da485f97212c0da6c04231":{
      "scriptId":"u19"},
    "eda4b2d7231a42f9a0fad9271c683b3a":{
      "scriptId":"u20"},
    "fa564dc2748c4b698e20315f9d95a29b":{
      "scriptId":"u21"},
    "4b50a76f4f2446f2a85ab887cc63ad31":{
      "scriptId":"u22"},
    "f4d9b66fedd3446ebfd1112273dfccd9":{
      "scriptId":"u23"},
    "0e41ff2cd8404a0483c71ed71c945c17":{
      "scriptId":"u24"},
    "58aea97d99194dbda0ac2e317ccb17b0":{
      "scriptId":"u25"},
    "249c8974febd48cbaf13a0c12dc69b76":{
      "scriptId":"u26"},
    "ba8a5591e4314779bc6768e4285fbe26":{
      "scriptId":"u27"},
    "26d269e2285d4541a8342c7a959ef548":{
      "scriptId":"u28"},
    "9db9d2fcb6ad4e288e1b6409531663e5":{
      "scriptId":"u29"},
    "cffc14833b49443ba5e5d7c8a1459e0f":{
      "scriptId":"u30"},
    "003e722c97e14f0892db8b62de853873":{
      "scriptId":"u31"},
    "b0d327a8683e401d8f1c6fe597dec351":{
      "scriptId":"u32"},
    "36a8f4e5e9b34e4194e2022dee9a9295":{
      "scriptId":"u33"},
    "41966c6a8a5b45e6a036187f9993c6d1":{
      "scriptId":"u34"},
    "bd147b50d22e4446adff7ad7f49a7dff":{
      "scriptId":"u35"},
    "96deed4071e64c76a88ba1f540b9934f":{
      "scriptId":"u36"},
    "9956ca9cbaab4c6e86134b3255a28bfe":{
      "scriptId":"u37"},
    "632f344d438d440994a816631259bd7b":{
      "scriptId":"u38"},
    "2dea0359c08f4d93891bcb838105a400":{
      "scriptId":"u39"},
    "b834284fcebc4ceaa2bc4f2a1a986a0c":{
      "scriptId":"u40"},
    "8f8b49435c8c4e09b2dfefd323e922e5":{
      "scriptId":"u41"},
    "c6aa01b50518452cbc0cc5793fc9b0b0":{
      "scriptId":"u42"},
    "fb8454fb85744c2eb6f6ffb99b6883a4":{
      "scriptId":"u43"},
    "5ee594bf1ee74c6aa531d2ffb52d4569":{
      "scriptId":"u44"},
    "e1c060a95f58429aaf52c15788bcf071":{
      "scriptId":"u45"},
    "f8bee2adbb07442fb7b79b8f3578a6ec":{
      "scriptId":"u46"},
    "034a35b0595b4e6aaedf93af18b981ef":{
      "scriptId":"u47"},
    "524e8835daa743dc9155596525581771":{
      "scriptId":"u48"},
    "6957bd8c51dd4e6da5c3b1293413610d":{
      "scriptId":"u49"},
    "fa9d9941f6954383a4601453c4070af3":{
      "scriptId":"u50"},
    "480fc1049b3a46948ab964c7cd00807e":{
      "scriptId":"u51"},
    "0fe717a892564c3294e7b148e462079e":{
      "scriptId":"u52"},
    "62831ebf128a4df581cf1254a459be6b":{
      "scriptId":"u53"},
    "b851b07ee1f047c8b8b5a345fce7a676":{
      "scriptId":"u54"},
    "d79701254e5d467c9d2af32ddf8d6c7c":{
      "scriptId":"u55"},
    "c4620184f77440c59b530557260d6cef":{
      "scriptId":"u56"},
    "4b6df28f1d054304bd256d9b97821f4c":{
      "scriptId":"u57"},
    "94f1622e91664cf486626ecdac8902dc":{
      "scriptId":"u58"},
    "65d152ad0dfe4fbda3bcad8063bbc005":{
      "scriptId":"u59"},
    "fea425ecc8be4835af8b390bd157cd99":{
      "scriptId":"u60"},
    "2ccc3923dd6043c5857f5af99858a470":{
      "scriptId":"u61"},
    "f8af3e3fe5b747fea753c6eb631b5c8f":{
      "scriptId":"u62"},
    "cf43d632c3db426e85854a96d6a55010":{
      "scriptId":"u63"},
    "f86ce68a22d54a7c8e489d462c2159e8":{
      "scriptId":"u64"},
    "d6f6ed5c9ddc4ee08e185ee050c4ca76":{
      "scriptId":"u65"},
    "c32a4a1ac86e44f0a857689f96bb7584":{
      "scriptId":"u66"},
    "76e70511e87a4c9c95907248b5bbf6c2":{
      "scriptId":"u67"},
    "14d10306eaa34db5b1b96bdfc600c55f":{
      "scriptId":"u68"},
    "cfbd7c4472ab49b8890160eaa2f72213":{
      "scriptId":"u69"},
    "435dc1e45cbb43e197e54d080ffdb24d":{
      "scriptId":"u70"},
    "3f0d8f002226413ca9bed848202085be":{
      "scriptId":"u71"},
    "1656597f97a44a66849a4f8bc7af7f97":{
      "scriptId":"u72"},
    "8a6b198dcaff4b3cae6dce22b5bfa39c":{
      "scriptId":"u73"},
    "865fb93dbd2a466792846668f6c6d45d":{
      "scriptId":"u74"},
    "a6833d31b1394922b32cca3991ea64ac":{
      "scriptId":"u75"},
    "416b57fe866f4a4e873e67f8aed7eb7a":{
      "scriptId":"u76"},
    "517d6fcd72584f76bca3eb5e89468a3f":{
      "scriptId":"u77"},
    "245c91f5f492452e990d8bc0e23f840e":{
      "scriptId":"u78"},
    "4a61b11acda34459b742f8a60639b5dc":{
      "scriptId":"u79"},
    "a370d8eb554a4718ab958794e6dd7bd1":{
      "scriptId":"u80"},
    "54480a7563d74b178795868cbf382914":{
      "scriptId":"u81"},
    "8ee5284f11204eadabba87f2f98c7c3c":{
      "scriptId":"u82"},
    "a89ada7f093847fd84d7f7f89c5a9fb4":{
      "scriptId":"u83"},
    "cb5aa400d5a3435ab2fe8deb2bf2b1bc":{
      "scriptId":"u84"},
    "fa878a3955824ec7a65777c25375d2a0":{
      "scriptId":"u85"},
    "f12f4f4cb8ba40edb9d92ef88aead172":{
      "scriptId":"u86"},
    "7d8347a01d0c47689fb91cb1ee0b31a1":{
      "scriptId":"u87"},
    "8a212cafdbba4a2b83ce9d07e9295d11":{
      "scriptId":"u88"},
    "b310c80d422d435f9276c5d917f86b95":{
      "scriptId":"u89"},
    "89c8d080b88e408baa4c4edb9e8cd71d":{
      "scriptId":"u90"},
    "ff755626978a484cb0b71cb250b9ce4f":{
      "scriptId":"u91"},
    "bc426294bb434a2fbaff2156066c8fd6":{
      "scriptId":"u92"},
    "04f57f056be942b1a4415c86dbb8140c":{
      "scriptId":"u93"},
    "a81b72ff8d4f4fde8f2a593c330e9d83":{
      "scriptId":"u94"},
    "283a24884bcb4f468a94a4cd74436d8a":{
      "scriptId":"u95"},
    "d00f7a9c505a41278cb27799e64c29d4":{
      "scriptId":"u96"},
    "b907892bef064a7c9ff71f41a8bb6428":{
      "scriptId":"u97"},
    "f6ddebd0224a45559a8526afe86ff787":{
      "scriptId":"u98"},
    "53e2654cb86f4981ab86d24d869418a3":{
      "scriptId":"u99"},
    "2810b387cdc94ec5ae736dc89fb26bfb":{
      "scriptId":"u100"},
    "3fe380f7951b4dbfb20cb8df502d8dc5":{
      "scriptId":"u101"},
    "f936c507f2374b398fd82dd414dd5eab":{
      "scriptId":"u102"},
    "27456f636feb42b98fc7392b7ae0b289":{
      "scriptId":"u103"},
    "29cb45852af4442b8054a494b54c07e3":{
      "scriptId":"u104"},
    "02ac6106ab984385a2f287f3d2ac0520":{
      "scriptId":"u105"},
    "d4a62751e8284c22b2b5b7e703c9eab1":{
      "scriptId":"u106"}}});